import {test,expect} from '@playwright/test';import {readFileSync} from 'node:fs';
const release=JSON.parse(readFileSync('dist/release-manifest.json')).release;
const root=`/releases/${release}/client/repository/local.js`;
const open=async(page,path='/')=>{await page.goto(path);await expect(page.locator('[data-start]')).toBeEnabled();};
const report=async page=>{await page.getByRole('button',{name:'Report after playing',exact:true}).click();await page.getByRole('button',{name:'Report that I completed it',exact:true}).click();await page.getByRole('button',{name:'Add to a player’s history',exact:true}).click();};
const snapshot=page=>page.evaluate(async root=>{const {LocalRepository}=await import(root);const r=new LocalRepository();const s=await r.snapshot();r.close();return s;},root);
async function create(page,name=''){await page.getByRole('button',{name:'New player',exact:true}).click();await expect(page.getByLabel('Nickname (optional)',{exact:true})).toBeVisible();if(name)await page.getByLabel('Nickname (optional)',{exact:true}).fill(name);await expect(page.getByRole('button',{name:'Create player',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Create player',exact:true}).click();await expect(page.locator('[data-view=attribution]')).toBeVisible();await expect(page.getByRole('radio',{name:name||'Player 1',exact:true})).toBeVisible();}
test('optional minimum model, explicit target/save, rename, correction and private network boundary',async({page},info)=>{
 const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({url:r.url(),body:r.postData(),method:r.method()}));await open(page);await report(page);await create(page,'SYNTHETIC_KITE');await page.screenshot({path:`.test-results/m3-attribution-${info.project.name}.png`,fullPage:true});
 await expect(page.getByRole('radio')).not.toBeChecked();await expect(page.getByRole('button',{name:'Save to selected player',exact:true})).toBeDisabled();let s=await snapshot(page);expect(s.records).toHaveLength(0);expect(Object.keys(s.players[0]).sort()).toEqual(['id','label','nickname','revision']);await page.getByRole('radio',{name:'SYNTHETIC_KITE'}).check();await page.getByRole('button',{name:'Save to selected player',exact:true}).evaluate(b=>{b.click();b.click();});await expect(page.getByText(/This report was added to/)).toBeVisible();await page.screenshot({path:`.test-results/m3-record-${info.project.name}.png`,fullPage:true});s=await snapshot(page);expect(s.records).toHaveLength(1);expect(s.operations).toHaveLength(1);expect(s.records[0].report.roundId).toBeNull();
 await page.getByRole('button',{name:'Correct attribution',exact:true}).click();await create(page,'SYNTHETIC_MOON');await page.getByRole('radio',{name:'SYNTHETIC_MOON'}).check();await page.getByRole('button',{name:'Move record to selected player',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('button',{name:'Go back',exact:true})).toBeFocused();await page.getByRole('dialog').getByRole('button',{name:'Move record to selected player',exact:true}).click();await expect(page.getByText(/This report was added to/)).toBeVisible();s=await snapshot(page);expect(s.records).toHaveLength(1);expect(s.records[0].revision).toBe(2);expect(s.records[0].targetId).toBe(s.players.find(p=>p.nickname==='SYNTHETIC_MOON').id);
 await page.getByRole('button',{name:'Player options',exact:true}).click();await page.getByRole('button',{name:'SYNTHETIC_MOON',exact:true}).click();await page.getByLabel('Nickname (optional)',{exact:true}).fill('SYNTHETIC_STAR');await page.getByRole('button',{name:'Save nickname',exact:true}).click();await expect(page.getByText('The nickname was updated in this browser.',{exact:true})).toBeVisible();expect((await snapshot(page)).records).toHaveLength(1);
 const leak=JSON.stringify(requests);for(const p of s.players){expect(leak).not.toContain(p.id);expect(leak).not.toContain(p.nickname);}expect(leak).not.toContain(s.records[0].report.id);expect(requests.every(r=>r.method==='GET')).toBe(true);expect(requests.every(r=>new URL(r.url).origin==='http://127.0.0.1:8919')).toBe(true);expect(JSON.stringify(await page.evaluate(()=>({history:history.state,session:{...sessionStorage},local:{...localStorage},url:location.href})))).not.toMatch(/SYNTHETIC_|targetId|reportId/);expect(errors).toEqual([]);
});
test('transaction identity survives concurrent saves, crash/reload, late deletion and stale mutation',async({page,context})=>{
 await open(page);const seed=await page.evaluate(async root=>{const {LocalRepository}=await import(root);const r=new LocalRepository(),s=await r.snapshot(),p=await r.create({epoch:s.epoch});const report={id:'synthetic-report',missionId:'m25',mechanicsVersion:'fixture',roundId:null,value:'complete',revision:1};const input={id:'synthetic-op',epoch:s.epoch,targetId:p.id,targetRevision:p.revision,report};const ops=await Promise.all([r.prepare(input),r.prepare({...input,id:'synthetic-duplicate'})]);return {input,p,ids:ops.map(o=>o.id)};},root);expect(seed.ids[0]).toBe(seed.ids[1]);await page.reload();let s=await snapshot(page);expect(s.records).toHaveLength(0);expect(s.operations[0].status).toBe('pending');
 const other=await context.newPage();await open(other);await Promise.all([page.evaluate(async({root,input})=>{const {LocalRepository}=await import(root);return new LocalRepository().commit(input.id,input.epoch);},{root,input:seed.input}),other.evaluate(async({root,input})=>{const {LocalRepository}=await import(root);return new LocalRepository().commit(input.id,input.epoch);},{root,input:seed.input})]);s=await snapshot(page);expect(s.records).toHaveLength(1);expect(s.operations).toHaveLength(1);
 const result=await page.evaluate(async({root,seed})=>{const {LocalRepository}=await import(root);const r=new LocalRepository();await r.deletePlayer({epoch:seed.input.epoch,id:seed.p.id,revision:1});const rejected=[];for(const fn of [()=>r.commit(seed.input.id,seed.input.epoch),()=>r.prepare(seed.input),()=>r.rename({epoch:seed.input.epoch,id:seed.p.id,revision:1,name:'late'})]){try{await fn();rejected.push(false);}catch{rejected.push(true);}}await r.deleteAll(seed.input.epoch);try{await r.create({epoch:seed.input.epoch,name:'late'});rejected.push(false);}catch{rejected.push(true);}return {rejected,snapshot:await r.snapshot()};},{root,seed});expect(result.rejected).toEqual([true,true,true,true]);expect(result.snapshot.players).toHaveLength(0);expect(result.snapshot.records).toHaveLength(0);expect(result.snapshot.operations).toHaveLength(0);
});
test('quota abort is atomic; denied, blocked and versionchange are honest and recoverable',async({page})=>{
 await open(page);const result=await page.evaluate(async root=>{const {LocalRepository,DATABASE}=await import(root);const r=new LocalRepository(),s=await r.snapshot(),p=await r.create({epoch:s.epoch});const op=await r.prepare({id:'quota-op',epoch:s.epoch,targetId:p.id,targetRevision:1,report:{id:'quota-report',missionId:'m25',mechanicsVersion:'fixture',roundId:null,value:'early',revision:1}});const add=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(value){if(this.name==='records')throw new DOMException('synthetic quota','QuotaExceededError');return add.call(this,value);};let failed=false;try{await r.commit(op.id,s.epoch);}catch{failed=true;}IDBObjectStore.prototype.add=add;const after=await r.snapshot();const recovered=await r.commit(op.id,s.epoch);let denied=false;try{await new LocalRepository(null).snapshot();}catch{denied=true;}const db=await r.open();db.dispatchEvent(new Event('versionchange'));const reopened=await r.snapshot();r.close();
 // A deliberately older synthetic database holds an upgrade open; no user data.
 const req=indexedDB.open('synthetic-blocked',1);const blocker=await new Promise(resolve=>{req.onupgradeneeded=()=>{};req.onsuccess=()=>resolve(req.result);});const blockedRepo=new LocalRepository({open(){return indexedDB.open('synthetic-blocked',2);}});let blocked=false;try{await blockedRepo.snapshot();}catch{blocked=true;}blocker.close();return {failed,after,recovered:recovered.status,denied,reopened:reopened.records.length,blocked};},root);expect(result.failed).toBe(true);expect(result.after.records).toHaveLength(0);expect(result.after.operations[0].status).toBe('pending');expect(result.recovered).toBe('committed');expect(result.denied).toBe(true);expect(result.reopened).toBe(1);expect(result.blocked).toBe(true);
});
test('delete scope cancels safely, removes one then all including legacy, preserves unrelated preferences',async({page})=>{
 await open(page);await report(page);await create(page);await page.getByRole('radio',{name:'Player 1',exact:true}).check();await page.getByRole('button',{name:'Save to selected player',exact:true}).click();await expect(page.getByText(/This report was added to/)).toBeVisible();await page.getByRole('button',{name:'Player options',exact:true}).click();await page.getByRole('button',{name:'Player 1',exact:true}).click();await page.getByRole('button',{name:'Delete this player and history',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Other players and legacy data remain');await page.keyboard.press('Escape');expect((await snapshot(page)).players).toHaveLength(1);await page.getByRole('button',{name:'Delete this player and history',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Delete this player and history',exact:true}).click();await expect(page.getByText('The selected local data was deleted.',{exact:true})).toBeVisible();expect((await snapshot(page)).records).toHaveLength(0);
 await page.evaluate(()=>{localStorage.setItem('jumvi_profiles_v1','synthetic raw');localStorage.setItem('jumvi_team_s_p1_p2_missions_done_v3','synthetic');localStorage.setItem('jumvi_p9_team_t3_cert_name_v1','synthetic');localStorage.setItem('jumvi_sound_on_v1','1');localStorage.setItem('unrelated','keep');});await page.getByRole('button',{name:'Delete all local player and history data',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Previously downloaded backups are not deleted');await page.getByRole('dialog').getByRole('button',{name:'Delete all local player and history data',exact:true}).click();await expect(page.getByText('The selected local data was deleted.',{exact:true})).toBeVisible();expect(await page.evaluate(()=>({...localStorage}))).toEqual({jumvi_sound_on_v1:'1',unrelated:'keep'});
});
test('TR disclosure, nickname only, 200% reflow, guest preserves prior report without attribution',async({page})=>{
 await open(page,'/tr');await page.getByRole('button',{name:'Oyun sonrası bildirim',exact:true}).click();await page.getByRole('button',{name:'Tamamladığımı bildir',exact:true}).click();await page.getByRole('button',{name:'Başka biri oynayacak',exact:true}).click();await page.getByRole('button',{name:'Oyuncusuz yeni oyuna geç',exact:true}).click();await expect(page.locator('[data-view=entry]')).toBeVisible();await page.getByRole('button',{name:'Yeniden oyun',exact:true}).click();await page.getByRole('button',{name:'Önceki tura dön',exact:true}).click();await expect(page.getByText('Görevi tamamladığını bildirdin.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Kişisel geçmişe ekle',exact:true}).click();await page.getByRole('button',{name:'Yeni oyuncu',exact:true}).click();await expect(page.getByText(/Oyuncu geçmişi yalnızca bu cihazdaki bu tarayıcıda saklanır/)).toBeVisible();await expect(page.locator('input')).toHaveCount(1);await page.setViewportSize({width:320,height:844});await page.evaluate(()=>document.documentElement.style.fontSize='200%');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(321);await expect(page.getByLabel('Takma ad (isteğe bağlı)',{exact:true})).toBeVisible();
});
test('late commit cannot overwrite a changed screen, and a deletion in another tab fences the delayed operation',async({page,context})=>{
 await open(page);await report(page);await create(page,'SYNTHETIC_LATE');await page.getByRole('radio',{name:'SYNTHETIC_LATE',exact:true}).check();
 await page.evaluate(async root=>{const {LocalRepository}=await import(root);const commit=LocalRepository.prototype.commit;window.syntheticCommitGate=new Promise(resolve=>window.releaseSyntheticCommit=resolve);LocalRepository.prototype.commit=async function(...args){await window.syntheticCommitGate;return commit.apply(this,args);};},root);
 await page.getByRole('button',{name:'Save to selected player',exact:true}).click();await expect(page.getByText('The record is being checked. You can return to play.',{exact:true})).toBeVisible();await expect.poll(async()=> (await snapshot(page)).operations.length).toBe(1);
 await page.getByRole('button',{name:'Back to the mission',exact:true}).click();await expect(page.locator('[data-view=returning]')).toBeVisible();
 const other=await context.newPage();await open(other);await other.evaluate(async root=>{const {LocalRepository}=await import(root);const r=new LocalRepository(),s=await r.snapshot();await r.deletePlayer({epoch:s.epoch,id:s.players[0].id,revision:s.players[0].revision});new BroadcastChannel('jumvi-local-invalidation-v1').postMessage('changed');r.close();},root);
 await page.evaluate(()=>window.releaseSyntheticCommit());await expect(page.locator('[data-view=returning]')).toBeVisible();await expect(page.getByText(/This report was added to/)).toHaveCount(0);
 // The pending promise is settled by an explicit verification request, not an arbitrary sleep.
 await expect.poll(async()=> (await snapshot(page)).records.length).toBe(0);expect((await snapshot(page)).operations).toHaveLength(0);expect((await snapshot(page)).players).toHaveLength(0);
});
test('reload reconciles a persisted pending operation through management without copying legacy records',async({page})=>{
 await open(page);await page.evaluate(async root=>{localStorage.setItem('jumvi_profiles_v1','[{"id":"p1","name":"SYNTHETIC_LEGACY"}]');localStorage.setItem('jumvi_p1_missions_done_v3','[25]');const {LocalRepository}=await import(root);const r=new LocalRepository(),s=await r.snapshot(),p=await r.create({epoch:s.epoch});await r.prepare({id:'synthetic-reload-op',epoch:s.epoch,targetId:p.id,targetRevision:p.revision,report:{id:'synthetic-reload-report',missionId:'m25',mechanicsVersion:'fixture',roundId:null,value:'early',revision:1}});r.close();},root);await page.reload();await page.getByRole('button',{name:'Player options',exact:true}).click();await expect(page.getByText(/Legacy local player\/history data is present/)).toBeVisible();await expect(page.getByText('SYNTHETIC_LEGACY',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Open record status · Player 1',exact:true}).click();await page.getByRole('button',{name:'Check / retry the same operation',exact:true}).click();await expect(page.getByText(/This report was added to/)).toBeVisible();const s=await snapshot(page);expect(s.records).toHaveLength(1);expect(s.records[0].id).toBe('synthetic-reload-op');expect(s.records[0].report.value).toBe('early');expect(await page.evaluate(()=>localStorage.getItem('jumvi_p1_missions_done_v3'))).toBe('[25]');
});
test('blocked IndexedDB never blocks play or claims a personal record',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(window,'indexedDB',{get(){throw new DOMException('synthetic denied','SecurityError');}}));await open(page);await report(page);await expect(page.getByText(/Local records are unavailable right now/)).toBeVisible();await expect(page.getByRole('button',{name:'Save to selected player',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Return without saving',exact:true}).click();await page.getByRole('button',{name:'Play again',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Continue without saving',exact:true}).click();await expect(page.locator('[data-view=active]')).toBeVisible();
});
test('failed creation preserves nickname input, and concurrent changes keep typing focus without claiming authentication',async({page,context})=>{
 await open(page);await report(page);await page.getByRole('button',{name:'New player',exact:true}).click();const input=page.getByLabel('Nickname (optional)',{exact:true});await input.fill('SYNTHETIC_DRAFT');
 await page.evaluate(async root=>{const {LocalRepository}=await import(root);window.syntheticCreate=LocalRepository.prototype.create;LocalRepository.prototype.create=async()=>{throw new DOMException('synthetic quota','QuotaExceededError');};},root);await page.getByRole('button',{name:'Create player',exact:true}).click();await expect(page.locator('.personal-message')).toContainText('Local records are unavailable');await expect(input).toHaveValue('SYNTHETIC_DRAFT');expect((await snapshot(page)).players).toHaveLength(0);await input.focus();
 const other=await context.newPage();await open(other);await other.evaluate(async root=>{const {LocalRepository}=await import(root);const r=new LocalRepository(),s=await r.snapshot();await r.create({epoch:s.epoch});new BroadcastChannel('jumvi-local-invalidation-v1').postMessage('changed');r.close();},root);await page.bringToFront();await expect(input).toHaveValue('SYNTHETIC_DRAFT');await expect(input).toBeFocused();await page.evaluate(async root=>{const {LocalRepository}=await import(root);LocalRepository.prototype.create=window.syntheticCreate;},root);await page.getByRole('button',{name:'Create player',exact:true}).click();await expect(page.getByRole('radio',{name:'SYNTHETIC_DRAFT',exact:true})).toBeVisible();expect((await snapshot(page)).players).toHaveLength(2);await expect(page.getByRole('radio',{name:'SYNTHETIC_DRAFT',exact:true})).not.toBeChecked();
});
test('corrupt control state cannot produce a verified save or block physical play',async({page})=>{
 await open(page);await page.evaluate(async root=>{const {LocalRepository}=await import(root);const r=new LocalRepository();await r.transaction('readwrite',async s=>{s.meta.delete('control');});r.close();},root);await page.getByRole('button',{name:'Player options',exact:true}).click();await expect(page.getByText(/Local records are unavailable right now/)).toBeVisible();await expect(page.getByRole('button',{name:'Delete all local player and history data',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Back to the mission',exact:true}).click();await page.getByRole('button',{name:'Back to the mission',exact:true}).click();await page.locator('[data-start]').click();await expect(page.locator('[data-view=active]')).toBeVisible();
});
