import {test,expect} from '@playwright/test';
test('m03 help presents canonical timing beside the matching art moment',async({page})=>{
 await page.goto('/tr');await expect(page.locator('[data-start]')).toBeEnabled();
 await page.getByRole('button',{name:'Başka uygun görev',exact:true}).click();
 await page.locator('[data-mission-id=m03] button').click();
 await page.getByRole('button',{name:'Açıklama / yardım',exact:true}).click();
 const root=await page.locator('script[type=module]').getAttribute('src');
 const prefix=root.split('/client/')[0];
 const steps=await page.evaluate(async prefix=>(await (await fetch(prefix+'/content/missions/m03.json')).json()).locale.tr.steps,prefix);
 const cards=page.locator('.steps > li');
 await expect(cards).toHaveCount(3);
 await expect(cards.nth(0)).toContainText(steps[0]);
 await expect(cards.nth(0)).toContainText(steps[1]);
 await expect(cards.nth(1)).toContainText(steps[2]);
 await expect(cards.nth(2)).not.toContainText(steps[0]);
 await expect(cards.nth(2)).not.toContainText(steps[1]);
 await expect(cards.nth(2)).not.toContainText(steps[2]);
 await expect(page.locator('.canonical-steps')).toHaveCount(0);
});
// Two separate moments suffice where they preserve every canonical rule and the catch/detach distinction.
test('all 36 EN/TR missions expose canonical instructions and hash-bound art files without profile or audio',async({page})=>{test.setTimeout(180000);const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const locale of ['tr','en-US']){await page.goto(locale==='tr'?'/tr':'/');await expect(page.locator('[data-start]')).toBeEnabled();const root=await page.locator('script[type=module]').getAttribute('src');const prefix=root.split('/client/')[0];const catalog=await page.evaluate(p=>fetch(p+'/content/catalog.json').then(r=>r.json()),prefix);for(const m of catalog.missions){await page.getByRole('button',{name:locale==='tr'?'Başka uygun görev':'Find another suitable mission',exact:true}).click();await page.locator(`[data-mission-id=${m.id}] button`).click();await expect(page.locator('h1')).toHaveText(m.titles[locale]);await expect(page.locator('[data-start]')).toBeEnabled();await page.getByRole('button',{name:locale==='tr'?'Açıklama / yardım':'How to play / help',exact:true}).click();await expect(page.locator('.steps li').first()).toBeVisible();const headings=await page.locator('.steps>li>h2').allTextContents();expect(headings.every(h=>h.split(/\s+/).length<=9)).toBe(true);expect(await page.locator('.steps li').count()).toBeGreaterThanOrEqual(2);if(m.id!=='m25'){const canonical=await page.evaluate(async({prefix,id,locale})=>{const source=await fetch(prefix+'/content/missions/'+id+'.json').then(r=>r.json()),presentation=await fetch(prefix+'/content/customer-presentation-v1.json').then(r=>r.json());return presentation.missions[id].customerCopy?.[locale]?.steps||source.locale[locale].steps;},{prefix,id:m.id,locale});const shown=await page.locator('[data-view=help]').innerText();for(const step of canonical)expect(shown).toContain(step);}else expect(await page.locator('.steps li').count()).toBe(3);await expect.poll(()=>page.locator('.steps img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0))).toBe(true);await page.getByRole('button',{name:locale==='tr'?'Göreve dön':'Back to the mission',exact:true}).first().click();}}expect(errors).toEqual([]);});
test('wrong critical-art bytes block Start; retry and mission-switch cannot inherit readiness',async({page})=>{await page.route('**/assets/mission-illustrations/customer-recovery-v1/m04-3.webp',r=>r.fulfill({status:200,contentType:'image/webp',body:Buffer.from('wrong bytes')}));await page.goto('/tr');await expect(page.locator('[data-start]')).toBeEnabled();await page.getByRole('button',{name:'Başka uygun görev',exact:true}).click();await page.locator('[data-mission-id=m04] button').click();await expect(page.locator('[data-readiness]')).toContainText('');await expect(page.locator('[data-start]')).toBeDisabled();await page.unroute('**/assets/mission-illustrations/customer-recovery-v1/m04-3.webp');await page.locator('[data-readiness] button').click();await expect(page.locator('[data-start]')).toBeEnabled();await page.getByRole('button',{name:'Başla',exact:true}).click();await page.reload();await expect(page.locator('[data-view=interrupted]')).toBeVisible();await expect(page.locator('.mission-label')).toHaveText('El Değiştir');});
test('wrong mission record at a valid URL is rejected before changing mission identity',async({page})=>{await page.route('**/content/missions/m04.json',async route=>{const original=await route.fetch(),body=await original.json();body.locale.tr.title='WRONG_VERSION_SYNTHETIC';await route.fulfill({response:original,json:body});});await page.goto('/tr');await expect(page.locator('[data-start]')).toBeEnabled();await page.getByRole('button',{name:'Başka uygun görev',exact:true}).click();await page.locator('[data-mission-id=m04] button').click();await expect(page.locator('[data-view=availability]')).toBeVisible();await expect(page.getByText('WRONG_VERSION_SYNTHETIC')).toHaveCount(0);});
