import {test,expect} from '@playwright/test';import http from 'node:http';import {readFileSync,existsSync} from 'node:fs';import {resolve,extname} from 'node:path';
const current=JSON.parse(readFileSync('dist/release-manifest.json')).release;
const mime={'.txt':'text/plain','.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.png':'image/png','.woff2':'font/woff2','.ttf':'font/ttf','.svg':'image/svg+xml'};
test('exact v254 → direct new, waiting old tabs, rollback and forward preserve synthetic data',async({browser})=>{test.setTimeout(180000);let mode='old';const server=http.createServer((req,res)=>{const path=new URL(req.url,'http://local').pathname,logical=path==='/'?'/index.html':['/tr','/tr/'].includes(path)?'/tr/index.html':path;if(logical==='/__test-control.html'){res.writeHead(200,{'Content-Type':'text/html','Cache-Control':'no-store'});res.end('<!doctype html><title>Synthetic migration control</title>');return;}let file=resolve('dist','.'+logical);if(mode==='old'&&['/index.html','/tr/index.html','/service-worker.js'].includes(logical))file=resolve('compat/v254','.'+logical);if(req.method!=='GET'||!existsSync(file)){res.writeHead(404);res.end('No');return;}res.writeHead(200,{'Content-Type':mime[extname(file)]||'application/octet-stream','Cache-Control':'no-store','Service-Worker-Allowed':'/'});res.end(readFileSync(file));});await new Promise(ok=>server.listen(0,'127.0.0.1',ok));const origin=`http://127.0.0.1:${server.address().port}`,context=await browser.newContext();await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());let page=await context.newPage();
try{await page.goto(origin);await page.evaluate(async()=>{localStorage.setItem('jumvi_profiles_v1','[{"id":"s1","name":"SYNTHETIC_LEGACY"}]');localStorage.setItem('foreign-key','keep');await navigator.serviceWorker.ready;});await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller).catch(()=>false)).toBe(true);await page.waitForLoadState('networkidle');const oldCache=await page.evaluate(()=>caches.has('jumvi-missions-v254'));expect(oldCache).toBe(true);const oldContent=await page.evaluate(()=>window.syntheticDocumentMarker=crypto.randomUUID());mode='new';await page.evaluate(async()=>{await (await navigator.serviceWorker.getRegistration()).update();});await expect.poll(()=>page.evaluate(async()=>!!(await navigator.serviceWorker.getRegistration()).waiting).catch(()=>false),{timeout:20000}).toBe(true);expect(await page.evaluate(()=>window.syntheticDocumentMarker)).toBe(oldContent);const newer=await context.newPage();await newer.goto(origin+'/tr');await expect(newer.locator('[data-start]')).toBeEnabled();expect(await newer.evaluate(()=>localStorage.getItem('jumvi_profiles_v1'))).toContain('SYNTHETIC_LEGACY');await newer.evaluate(async rel=>{const {LocalRepository}=await import(`/releases/${rel}/client/repository/local.js`);const r=new LocalRepository(),s=await r.snapshot();await r.create({epoch:s.epoch,name:'SYNTHETIC_NEW'});r.close();},current);await page.close();await newer.close();page=await context.newPage();await page.goto(origin+'/tr');await expect(page.locator('[data-start]')).toBeEnabled();await expect.poll(()=>page.evaluate(async()=>!(await navigator.serviceWorker.getRegistration()).waiting),{timeout:20000}).toBe(true);expect(await page.evaluate(()=>caches.has('jumvi-missions-v254'))).toBe(true);
 // Move to a same-origin page without the app's controllerchange reload before rollback.
 await page.goto(origin+'/__test-control.html');await expect(page).toHaveTitle('Synthetic migration control');
 mode='old';await page.evaluate(async()=>{await (await navigator.serviceWorker.getRegistration()).update();});await expect.poll(()=>page.evaluate(rel=>caches.has(`jumvi-lock09-${rel}-shell`),current)).toBe(false);await page.goto(origin);await page.waitForLoadState('networkidle');await expect.poll(()=>page.evaluate(async()=>!(await navigator.serviceWorker.getRegistration()).installing).catch(()=>false)).toBe(true);expect(await page.evaluate(()=>localStorage.getItem('foreign-key'))).toBe('keep');const snap=await page.evaluate(async rel=>{const {LocalRepository}=await import(`/releases/${rel}/client/repository/local.js`);const r=new LocalRepository(),s=await r.snapshot();r.close();return s;},current);expect(snap.players).toHaveLength(1);expect(snap.players[0].nickname).toBe('SYNTHETIC_NEW');
 // The exact archived app re-registers its query-versioned worker and can reload on controllerchange.
 // After proving the rollback UI/data, use a same-origin controlled tab without app-side registration races.
 await page.goto(origin+'/__test-control.html');await expect(page).toHaveTitle('Synthetic migration control');
 mode='new';await page.evaluate(async()=>{await (await navigator.serviceWorker.getRegistration()).update();});await expect.poll(()=>page.evaluate(async()=>!!(await navigator.serviceWorker.getRegistration()).waiting).catch(()=>false),{timeout:20000}).toBe(true);await page.close();page=await context.newPage();await page.goto(origin+'/tr');await expect(page.locator('[data-start]')).toBeEnabled();expect(await page.evaluate(()=>localStorage.getItem('foreign-key'))).toBe('keep');
}finally{await context.close();await new Promise(ok=>server.close(ok));}});
