import {test as base,expect} from '@playwright/test';import {readFileSync,existsSync,statSync} from 'node:fs';import http from 'node:http';import {resolve,extname} from 'node:path';import worker from '../../src/m0-staging-worker.mjs';
const mime={'.txt':'text/plain','.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.woff2':'font/woff2','.ttf':'font/ttf'};
const test=base.extend({network:async({},use)=>{const n={up:true};const server=http.createServer(async(req,res)=>{if(!n.up){res.writeHead(503,{'Content-Type':'text/plain','Cache-Control':'no-store'});res.end('Synthetic origin outage');return;}const u=new URL(req.url,'https://jumvi-missions-staging.saykirtasiye.workers.dev');const r=await worker.fetch(new Request(u,{headers:req.headers,method:req.method}),{ASSETS:{fetch:async request=>{const p=resolve('dist','.'+new URL(request.url).pathname);if(!existsSync(p)||!statSync(p).isFile())return new Response('No',{status:404});return new Response(readFileSync(p),{headers:{'Content-Type':mime[extname(p)]||'application/octet-stream'}});}}});res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()));});await new Promise(ok=>server.listen(0,'127.0.0.1',ok));n.origin=`http://127.0.0.1:${server.address().port}`;await use(n);server.closeAllConnections();await new Promise(ok=>server.close(ok));}});
const release=JSON.parse(readFileSync('dist/release-manifest.json')).release;
async function controlled(page,origin){await page.goto(origin+'/tr');await expect(page.locator('[data-start]')).toBeEnabled();await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await expect(page.locator('[data-start]')).toBeEnabled();}
async function warm(page,id){return page.evaluate(async({release,id})=>{const reg=await navigator.serviceWorker.ready;return new Promise(resolve=>{const ch=new MessageChannel();ch.port1.onmessage=e=>resolve(e.data.ready);reg.active.postMessage({type:'CACHE_MISSION',id,release},[ch.port2]);});},{release,id});}
test('release-scoped offline TR/EN shell, visited mission, uncached mission and local data preservation',async({page,context,network})=>{await controlled(page,network.origin);await page.evaluate(()=>{localStorage.setItem('jumvi_profiles_v1','[{"id":"synthetic","name":"SYNTHETIC_ONLY"}]');localStorage.setItem('foreign-key','keep');});await page.getByRole('button',{name:'Başka uygun görev',exact:true}).click();await page.locator('[data-mission-id=m04] button').click();await expect(page.locator('[data-start]')).toBeEnabled();expect(await warm(page,'m04')).toBe(true);network.up=false;await page.reload();await expect(page.locator('h1')).toHaveText('El Değiştir');await expect(page.locator('[data-start]')).toBeEnabled();await page.goto(network.origin+'/');await expect(page.locator('h1')).toHaveText('Switcharoo');await expect(page.locator('[data-start]')).toBeEnabled();await page.getByRole('button',{name:'Find another suitable mission',exact:true}).click();await page.locator('[data-mission-id=m34] button').click();await expect(page.locator('[data-view=availability]')).toBeVisible({timeout:12000});expect(await page.evaluate(()=>localStorage.getItem('foreign-key'))).toBe('keep');expect(await page.evaluate(()=>localStorage.getItem('jumvi_profiles_v1'))).toContain('SYNTHETIC_ONLY');network.up=true;});
test('protected paths, authorized responses and unknown URLs never enter app caches',async({page,network})=>{await controlled(page,network.origin);const result=await page.evaluate(async()=>{const paths=['/panel','/analiz','/api/private','/data/test.json','/src/worker.js','/unknown'];const status=[];for(const p of paths)status.push((await fetch(p)).status);const auth=await fetch('/',{headers:{Authorization:'Bearer SYNTHETIC_NOT_A_SECRET'}});const keys=await caches.keys();const urls=[];for(const k of keys.filter(k=>k.startsWith('jumvi-lock09-')))for(const req of await (await caches.open(k)).keys())urls.push(new URL(req.url).pathname);return{status,auth:auth.status,urls};});expect(result.status.every(s=>s===404)).toBe(true);expect(result.auth).toBe(403);expect(result.urls.some(p=>/^\/(panel|analiz|api|data|src|unknown)/.test(p))).toBe(false);});
test('wrong locale cache response rejected; unrelated caches and synthetic storage retained',async({page,context,network})=>{await controlled(page,network.origin);await page.evaluate(async release=>{const c=await caches.open(`jumvi-lock09-${release}-shell`),en=await c.match('/index.html');await c.put('/tr/index.html',en);await (await caches.open('foreign-cache')).put('/synthetic',new Response('keep'));},release);network.up=false;const status=await page.evaluate(()=>fetch('/tr').then(r=>r.status));expect(status).toBe(503);expect(await page.evaluate(()=>caches.has('foreign-cache'))).toBe(true);network.up=true;});
