import {test,expect} from '@playwright/test';
const open=async(page,path='/')=>{await page.goto(path);await expect(page.locator('[data-start]')).toBeEnabled();};
for(const locale of ['en-US','tr']){
const tr=locale==='tr';
test(`M6 group instructions preserve canonical player counts (${locale})`,async({page})=>{
 await open(page,tr?'/tr':'/');
 for(const id of ['m20','m21','m27']){
  await page.getByRole('button',{name:tr?'Başka uygun görev':'Find another suitable mission',exact:true}).click();await page.locator(`[data-mission-id=${id}] button`).click();await expect(page.locator('[data-start]')).toBeEnabled();
  const materials=await page.locator('.materials').innerText();await page.getByRole('button',{name:tr?'Yeniden oyun':'Play again',exact:true}).click();await page.getByRole('button',{name:tr?'Birlikte oyun':'Play together',exact:true}).click();await expect(page.locator('main')).toContainText(materials);await expect(page.locator('main')).not.toContainText(tr?'Bu görev iki kişiyle oynanır.':'This mission is played by two people.');await page.getByRole('button',{name:tr?'Ayrıl':'Leave',exact:true}).click();
 }
});
test(`M6 correcting an older mission shows and preserves the recorded mission (${locale})`,async({page})=>{
 await open(page,tr?'/tr':'/');const prefix=(await page.locator('script[type=module]').getAttribute('src')).split('/client/')[0];
 const title=await page.evaluate(async({prefix,locale})=>{const {LocalRepository}=await import(prefix+'/client/repository/local.js');const r=new LocalRepository(),s=await r.snapshot(),p=await r.create({epoch:s.epoch}),mission=await fetch(prefix+'/content/missions/m20.json').then(r=>r.json());await r.create({epoch:s.epoch});await r.prepare({id:'synthetic-m6-op',epoch:s.epoch,targetId:p.id,targetRevision:p.revision,report:{id:'synthetic-m6-report',missionId:'m20',mechanicsVersion:mission.mechanicsVersion,roundId:null,value:'complete',revision:1}});await r.commit('synthetic-m6-op',s.epoch);r.close();return mission.locale[locale].title;},{prefix,locale});
 await page.getByRole('button',{name:tr?'Oyuncu işlemleri':'Player options',exact:true}).click();await page.getByRole('button',{name:'Player 1',exact:true}).click();await expect(page.locator('.history-item')).toContainText(title);await page.getByRole('button',{name:tr?'Kayıt durumunu aç':'Open record status',exact:true}).click();await expect(page.locator('main')).toContainText(title);await page.getByRole('button',{name:tr?'Atfı düzelt':'Correct attribution',exact:true}).click();await expect(page.locator('main')).toContainText(title);await expect(page.locator('main')).not.toContainText(tr?'Sakin Yakala':'Chill Catch');await page.getByRole('radio',{name:'Player 2',exact:true}).check();await page.getByRole('button',{name:tr?'Kaydı seçili oyuncuya taşı':'Move record to selected player',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:tr?'Kaydı seçili oyuncuya taşı':'Move record to selected player',exact:true}).click();await expect(page.locator('main')).toContainText(title);
 await expect.poll(()=>page.evaluate(async prefix=>{const {LocalRepository}=await import(prefix+'/client/repository/local.js');const r=new LocalRepository(),s=await r.snapshot();r.close();return s.records.map(x=>({mission:x.report.missionId,owner:s.players.find(p=>p.id===x.targetId)?.label}));},prefix)).toEqual([{mission:'m20',owner:'Player 2'}]);
});
}
test('M6 utility layout respects enlarged text at and above the original CSS breakpoint',async({page})=>{
 await open(page,'/tr');for(const width of [320,390,430,640]){await page.setViewportSize({width,height:844});await page.evaluate(()=>{document.documentElement.style.fontSize='200%';dispatchEvent(new Event('resize'));});await expect(page.locator('.entry-support')).toHaveClass(/compact/);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);for(const b of await page.locator('.entry-support button').all())expect(await b.evaluate(b=>b.scrollWidth<=b.clientWidth+1)).toBe(true);}
});
test('M6 native dialog keyboard containment, Escape return, reduced motion and persisted page event',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await open(page);expect(await page.locator('[data-start]').evaluate(b=>getComputedStyle(b).transitionDuration)).toBe('0s');await page.getByRole('button',{name:'Report after playing',exact:true}).click();await page.getByRole('button',{name:'Report that I completed it',exact:true}).click();const replay=page.getByRole('button',{name:'Play again',exact:true});await replay.focus();await replay.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog').getByRole('button',{name:'Go back',exact:true})).toBeFocused();for(let i=0;i<4;i++){await page.keyboard.press('Tab');expect(await page.getByRole('dialog').evaluate(d=>d.contains(document.activeElement)||document.activeElement===document.body)).toBe(true);}await page.keyboard.press('Escape');await expect(replay).toBeFocused();await replay.click();await page.getByRole('dialog').getByRole('button',{name:'Continue without saving',exact:true}).click();await expect(page.locator('[data-view=active]')).toBeVisible();await page.evaluate(()=>dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await expect(page.locator('[data-view=interrupted]')).toBeVisible();await expect(page.getByText('No play result has been reported.',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Resume this round',exact:true}).click();await expect(page.locator('[data-view=active]')).toBeVisible();
});

test('M6 enlarged active labels retain whole words and reachable keyboard controls',async({page})=>{
 await page.setViewportSize({width:320,height:568});await open(page);await page.evaluate(()=>{document.documentElement.style.fontSize='200%';dispatchEvent(new Event('resize'));});await page.locator('[data-start]').click();
 for(const control of await page.locator('.active-control').all()){const split=await control.evaluate(b=>{const n=[...b.childNodes].find(n=>n.nodeType===Node.TEXT_NODE);if(!n)return ['missing label'];const bad=[];for(const m of n.textContent.matchAll(/\S+/g)){const range=document.createRange();range.setStart(n,m.index);range.setEnd(n,m.index+m[0].length);if([...range.getClientRects()].filter(r=>r.width>0).length>1)bad.push(m[0]);}return bad;});expect(split).toEqual([]);await control.focus();await expect(control).toBeFocused();}
 await page.getByRole('button',{name:'Stop this round',exact:true}).press('Enter');await expect(page.locator('[data-view=stopped]')).toBeVisible();
});
