import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
for(const tr of [false,true])test(`reference mission layout keeps rules, real equipment and useful controls ${tr?'TR':'EN'}`,async({page})=>{
 await page.goto(tr?'/tr/':'/');await expect(page.locator('[data-start]')).toBeEnabled();
 await expect(page.locator('.kit-facts li')).toHaveCount(3);await expect(page.locator('.kit-facts')).toContainText(tr?'1 top':'1 ball');await expect(page.locator('.entry-rules li')).toHaveCount(2);await expect(page.locator('.entry-rules')).toHaveAttribute('role','list');await expect(page.locator('.rule-number[aria-hidden=true]')).toHaveCount(2);
 const order=await page.evaluate(()=>['.entry-brief','.entry-hero','.mission-kit','.entry-actions'].map(q=>document.querySelector(q).getBoundingClientRect().top));expect(order).toEqual([...order].sort((a,b)=>a-b));
 await page.getByRole('button',{name:tr?'Başka uygun görev':'Find another suitable mission',exact:true}).click();await expect(page.locator('.featured-mission h2')).toHaveText(tr?'Sakin Yakala':'Chill Catch');await expect(page.locator('.featured-mission')).not.toContainText(/Suggested for you/);await expect(page.locator('.mission-list>li:visible')).toHaveCount(36);
 await page.locator('.discovery-filters>summary').click();await page.getByLabel(tr?'Kaç oyuncu var?':'How many players?',{exact:true}).selectOption('4');await expect(page.locator('.featured-mission')).toBeHidden();await page.getByRole('button',{name:tr?'Filtreleri temizle':'Clear filters',exact:true}).click();await expect(page.locator('.featured-mission')).toBeVisible();await page.locator('.featured-mission button').click();await expect(page.locator('[data-start]')).toBeEnabled();await page.locator('[data-start]').click();await expect(page.locator('h1')).toHaveText(tr?'Sakin Yakala':'Chill Catch');await expect(page.locator('.phone-away')).toBeVisible();await expect(page.locator('.active-actions button')).toHaveCount(2);
 for(const width of [320,390,430])for(const scale of [1,2]){await page.setViewportSize({width,height:844});await page.evaluate(scale=>{document.documentElement.style.fontSize=`${scale*100}%`;dispatchEvent(new Event('resize'));},scale);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);for(const b of await page.locator('.active-actions button').all()){const box=await b.boundingBox();expect(box.height).toBeGreaterThanOrEqual(64*scale);expect(box.x+box.width).toBeLessThanOrEqual(width);}}
 await page.addScriptTag({content:readFileSync('node_modules/axe-core/axe.min.js','utf8')});expect((await page.evaluate(()=>axe.run('#app'))).violations).toEqual([]);
 await page.locator('.active-actions button').first().click();await expect(page.locator('#first-step')).toBeVisible();await page.getByRole('button',{name:tr?'Tura dön':'Back to this round',exact:true}).first().click();await page.locator('.stop-action').click();await expect(page.locator('[data-view=stopped]')).toBeVisible();
});
