import {test,expect} from '@playwright/test';import {readFileSync} from 'node:fs';import {serveCoexist} from '../../tools/serve-v2-coexist.mjs';
const release=JSON.parse(readFileSync('dist-v2/v2/release-manifest.json')).release;
async function app(page,url,tr=false){await page.goto(url);await expect(page.locator('[data-start]')).toBeEnabled({timeout:45000});await expect(page.locator('html')).toHaveAttribute('lang',tr?'tr':'en-US');}
async function activeSW(page,scope){await expect.poll(()=>page.evaluate(async scope=>{const r=await navigator.serviceWorker.getRegistration(scope);return !!r?.active&&new URL(r.scope).pathname===scope;},scope),{timeout:60000}).toBe(true);}
test('promoted root EN/TR shares exact V2 records, preserves legacy and runs Help/Start/Stop',async({browser})=>{
 test.setTimeout(180000);const s=await serveCoexist(0,{promoted:true}),c=await browser.newContext();await c.route('**/*',r=>new URL(r.request().url()).origin===s.origin?r.continue():r.abort());const p=await c.newPage();
 try{
 await app(p,s.origin+'/v2/');await p.evaluate(async release=>{localStorage.setItem('jumvi_profiles_v1','[{"id":"p1","name":"SYNTHETIC_LEGACY","avatar":"monkey"}]');const {LocalRepository}=await import(`/v2/releases/${release}/client/repository/local.js`);const r=new LocalRepository(),snap=await r.snapshot();const player=await r.create({epoch:snap.epoch,name:'SYNTHETIC_SHARED'});const op=await r.prepare({id:crypto.randomUUID(),epoch:snap.epoch,targetId:player.id,targetRevision:player.revision,report:{id:'synthetic-report',missionId:'m25',mechanicsVersion:'qa-fixture',roundId:null,value:'complete',revision:1}});await r.commit(op.id,snap.epoch);r.close();},release);
 for(const tr of [false,true]){await app(p,s.origin+(tr?'/tr/':'/'),tr);expect(new URL(p.url()).pathname).toBe(tr?'/tr/':'/');const result=await p.evaluate(async release=>{const d=await import(`/v2/releases/${release}/client/deployment.js`);const {LocalRepository}=await import(`/v2/releases/${release}/client/repository/local.js`);const r=new LocalRepository(),snap=await r.snapshot();r.close();return {base:d.BASE,v2:d.IS_V2,names:snap.players.map(x=>x.nickname),records:snap.records.length,legacy:localStorage.getItem('jumvi_profiles_v1')};},release);expect(result).toEqual({base:'/',v2:true,names:['SYNTHETIC_SHARED'],records:1,legacy:'[{"id":"p1","name":"SYNTHETIC_LEGACY","avatar":"monkey"}]'});
 await p.getByRole('button',{name:tr?'Açıklama / yardım':'How to play / help',exact:true}).click();await expect(p.locator('#first-step')).toBeVisible();await p.getByRole('button',{name:tr?'Göreve dön':'Back to the mission',exact:true}).first().click();await p.locator('[data-start]').click();await p.locator('.active-control').nth(1).click();await expect(p.locator('[data-view=stopped]')).toBeVisible();await p.getByRole('button',{name:tr?'Ayrıl':'Leave',exact:true}).click();}
 await activeSW(p,'/');await p.reload();await expect(p.locator('[data-start]')).toBeEnabled();expect(await p.evaluate(()=>navigator.serviceWorker.controller.scriptURL)).toBe(s.origin+'/service-worker.js');
 for(const scope of ['/','/v2/']){const r=await c.request.get(s.origin+scope+'manifest.json');expect((await r.json()).id).toBe(scope);}
 const v1=await c.newPage();await v1.goto(s.origin+'/v1/');await expect(v1.locator('#todayHeroTitle').or(v1.locator('#btnWelcomeStart')).filter({visible:true}).first()).toBeVisible();await activeSW(v1,'/v1/');await v1.reload();await expect(v1.locator('#todayHeroTitle').or(v1.locator('#btnWelcomeStart')).filter({visible:true}).first()).toBeVisible();expect(await v1.evaluate(()=>navigator.serviceWorker.controller.scriptURL)).toBe(s.origin+'/v1/service-worker.js');
 await v1.goto(s.origin+'/v1/tr/');await expect(v1.locator('html')).toHaveAttribute('lang','tr');await expect(v1.locator('#todayHeroTitle').or(v1.locator('#btnWelcomeStart')).filter({visible:true}).first()).toBeVisible();expect(await v1.evaluate(()=>localStorage.getItem('jumvi_profiles_v1'))).toBe('[{"id":"p1","name":"SYNTHETIC_LEGACY","avatar":"monkey"}]');
 await s.stopOrigin();await p.goto(s.origin+'/');await expect(p.locator('[data-start]')).toBeEnabled();await p.goto(s.origin+'/tr/');await expect(p.locator('html')).toHaveAttribute('lang','tr');await expect(p.locator('[data-start]')).toBeEnabled();await v1.goto(s.origin+'/v1/');await expect(v1.locator('#todayHeroTitle').or(v1.locator('#btnWelcomeStart')).filter({visible:true}).first()).toBeVisible();await v1.goto(s.origin+'/v1/tr/');await expect(v1.locator('html')).toHaveAttribute('lang','tr');
 }finally{await c.close();await s.resumeOrigin();await new Promise(ok=>s.server.close(ok));}
});
for(const baseline of ['original','compat'])test(`old installed ${baseline} root upgrades without clearing V2/legacy records; rollback remains usable`,async({browser})=>{
 test.setTimeout(180000);const s=await serveCoexist(0,{legacySW:baseline}),c=await browser.newContext();await c.route('**/*',r=>new URL(r.request().url()).origin===s.origin?r.continue():r.abort());let p=await c.newPage();
 try{await p.goto(s.origin+'/');await activeSW(p,'/');await p.evaluate(()=>{localStorage.setItem('jumvi_profiles_v1','[{"id":"p1","name":"SYNTHETIC_KEEP","avatar":"monkey"}]');localStorage.setItem('jumvi-v2:appearance.v1','dark');});s.state.promoted=true;await app(p,s.origin+'/');await expect.poll(()=>p.evaluate(async()=>!!(await navigator.serviceWorker.getRegistration('/'))?.waiting),{timeout:60000}).toBe(true);await p.close();p=await c.newPage();await app(p,s.origin+'/');await expect.poll(()=>p.evaluate(async()=>caches.has('jumvi-home-'+document.querySelector('script[src*=releases]').src.split('/releases/')[1].split('/')[0]+'-shell'))).toBe(true);
 expect(await p.evaluate(()=>localStorage.getItem('jumvi_profiles_v1'))).toBe('[{"id":"p1","name":"SYNTHETIC_KEEP","avatar":"monkey"}]');expect(await p.evaluate(()=>localStorage.getItem('jumvi-v2:appearance.v1'))).toBe('dark');
 s.state.promoted=false;await p.goto(s.origin+'/');await expect(p.locator('#todayHeroTitle').or(p.locator('#btnWelcomeStart')).filter({visible:true}).first()).toBeVisible();await app(p,s.origin+'/v2/');expect(await p.evaluate(()=>localStorage.getItem('jumvi_profiles_v1'))).toBe('[{"id":"p1","name":"SYNTHETIC_KEEP","avatar":"monkey"}]');
 }finally{await c.close();await new Promise(ok=>s.server.close(ok));}
});
