// Data: missions, badges, packs helpers
const PACKS = [
  { key:"all", name:"All Packs" },
  { key:"Reflex Rush", name:"Reflex Rush" },
  { key:"Aim Master", name:"Aim Master" },
  { key:"Focus Control", name:"Focus Control" },
  { key:"Team Duo", name:"Team Duo" },
  { key:"Indoor Compact", name:"Indoor Compact" },
];

function m(id, pack, icon, title, difficulty, players, time, age, steps, win, safety, tip){
  return { id, pack, icon, title, difficulty, players, time, age, steps, win, safety, tip };
}

// 30 missions (5 packs × 6)
const missions = [
  // Reflex Rush (6)
  m(1,"Reflex Rush","⚡","Flash Catch",1,"2","45s","3+",
    ["Stand about 2 big steps apart (≈2 m).","Make quick, soft throws.","Catch fast and reset."],
    "Catch as many times as you can in 45 seconds!",
    "Keep throws below face level.",
    "Go slower for younger kids."),
  m(2,"Reflex Rush","🟢","Go / Stop Catch",1,"2-3","60s","4+",
    ["Throw only when someone says “GO”.","Freeze when someone says “STOP”.","Continue until timer ends."],
    "No drops during STOP = bonus point.",
    "Freeze means no throwing.",
    "Great for attention + control."),
  m(3,"Reflex Rush","👏","Clap-Then-Catch",2,"2","60s","6+",
    ["Throw gently.","Catcher claps once, then catches.","Switch roles after 10 throws."],
    "10 clean catches each wins.",
    "If it feels hard, remove the clap.",
    "Start with slow throws."),
  m(4,"Reflex Rush","🔁","Switch Hands",2,"2","90s","6+",
    ["Catch with right hand.","Next catch with left hand.","Alternate every throw."],
    "First to 12 clean catches wins.",
    "Keep distance steady.",
    "Builds both-hand coordination."),
  m(5,"Reflex Rush","🧊","Freeze & Catch",1,"2","60s","4+",
    ["After each catch, freeze 2 seconds.","Then throw back softly.","Repeat."],
    "No moving during freeze = win.",
    "No running.",
    "Simple indoor/outdoor game."),
  m(6,"Reflex Rush","🔊","Echo Count",1,"2","60s","3+",
    ["Throw and say the number aloud.","Catcher repeats the number.","Then throws back."],
    "Reach 15 without mistakes.",
    "Stay calm if mistakes happen.",
    "Adds memory + focus."),

  // Aim Master (6)
  m(7,"Aim Master","🎯","Target Ladder",2,"2","90s","4+",
    ["Put a sticker dot in the paddle center.","Start close (≈1.5 m) and aim for the dot.","After 5 hits, step back one big step."],
    "Get 8 dot hits in 12 throws.",
    "Keep throws below face level.",
    "Big dot first, then small dot."),
  m(8,"Aim Master","🟧","Ring Landing",2,"1-2","90s","4+",
    ["Make a tape ring on the floor between you.","Throw so the ball lands inside the ring.","Catcher lets it bounce once, then catches."],
    "Make 5 ring land-and-catches.",
    "Use a soft ball only.",
    "Keep the ring within 1–2 m."),
  m(9,"Aim Master","📏","Distance Ladder",2,"2","120s","5+",
    ["Start 1 m apart and make 3 clean catches.","Step back 0.5 m and repeat.","Stop at 3 m max."],
    "Reach 3 m with 3 clean catches.",
    "Stop if throws get wild.",
    "Smooth, gentle arcs only."),
  m(10,"Aim Master","🧠","Step‑Throw‑Back",2,"2","90s","6+",
    ["Step forward once.","Throw softly.","Step back and repeat."],
    "10 clean throws wins.",
    "Keep below face level.",
    "Adds body control."),
  m(11,"Aim Master","🪙","Slow Arc",1,"2","90s","3+",
    ["Throw high and slow.","Catcher waits calmly.","Catch with both hands if needed."],
    "10 slow catches wins.",
    "No rushing.",
    "Perfect for younger kids."),
  m(12,"Aim Master","🚪","Gate Pass",2,"2","120s","6+",
    ["Place two markers one paddle‑width apart as a gate.","Throw through the gate at chest‑low height.","Catcher catches and throws back."],
    "Complete 10 clean gate passes.",
    "Keep throws soft and low.",
    "Make the gate closer for younger kids."),

  // Focus Control (6)
  m(13,"Focus Control","🧘","Quiet Count",1,"2","120s","4+",
    ["No talking challenge.","After each catch, show the number with fingers.","Keep throws soft and steady."],
    "Reach 12 clean catches in silence.",
    "Take short breaks if needed.",
    "Great for calm focus."),
  m(14,"Focus Control","🐢","Slow–Fast Switch",2,"2","90s","4+",
    ["Do 5 slow throws.","Do 5 medium throws.","Repeat once."],
    "Finish 20 throws with no drops.",
    "Keep feet planted.",
    "Slow first, then steady."),
  m(15,"Focus Control","👀","Eyes on Ball",1,"2","90s","3+",
    ["Catcher says “I SEE IT”.","Throw gently.","Catcher catches and repeats."],
    "Reach 15 clean catches.",
    "Keep distance stable.",
    "Builds tracking skill."),
  m(16,"Focus Control","🫁","Count‑3 Catch",1,"2","90s","4+",
    ["Thrower counts 1‑2‑3.","Throw on 3.","Catcher catches and counts back."],
    "Complete 10 timed catches.",
    "Keep the count steady.",
    "Use a calm voice."),
  m(17,"Focus Control","🪞","Mirror Moves",2,"2","120s","6+",
    ["Player A chooses a simple, safe pose.","Player B copies, then both return to ready.","Throw and catch."],
    "Complete 8 pose‑and‑catch rounds.",
    "Pick balance‑safe poses.",
    "Keep it simple."),
  m(18,"Focus Control","🔟","Count to Ten",1,"2","90s","3+",
    ["Count every clean catch.","If you drop, restart.","Try again."],
    "Reach 10 clean catches.",
    "No stress, just retry.",
    "Classic confidence builder."),

  // Team Duo (6)
  m(19,"Team Duo","👨‍👩‍👧‍👦","Circle Pass",2,"3-6","180s","4+",
    ["Make a small circle.","Pass to anyone (not same person twice).","Keep it gentle."],
    "Complete 2 full minutes with no drops.",
    "Keep space between kids.",
    "Perfect party mode."),
  m(20,"Team Duo","🏁","Relay Pass",2,"4+","180s","5+",
    ["Make two lines (two teams).","Pass down the line.","After your pass, walk to the back."],
    "First team to 20 passes wins.",
    "No running if indoors.",
    "Keep throws low."),
  m(21,"Team Duo","🧑‍✈️","Call the Catcher",2,"3+","150s","6+",
    ["Choose a captain for 3 throws.","Captain calls the next catcher by name.","Switch captain every 3 throws."],
    "Complete 12 clean called throws.",
    "Keep voices friendly.",
    "Everyone gets a turn."),
  m(22,"Team Duo","🛡️","Quick Return",2,"3-5","180s","6+",
    ["If a ball drops, the nearest player picks it up.","Make a short soft return pass.","Keep a team count."],
    "10 quick returns wins.",
    "No diving on hard floors.",
    "Use short, soft passes."),
  m(23,"Team Duo","🔄","Partner Swap",2,"4+","180s","6+",
    ["Play 6 catches with a partner.","Then swap partners.","Repeat."],
    "Most clean swaps wins.",
    "Swap calmly, no pushing.",
    "Keeps everyone included."),
  m(24,"Team Duo","🏆","2v2 Team Count",2,"4","240s","6+",
    ["Two teams of two.","Each team does 5 clean catches, then switch.","Add all catches to one total."],
    "Reach 40 total team catches.",
    "Keep it friendly.",
    "Celebrate every clean catch."),

  // Indoor Compact (6)
  m(25,"Indoor Compact","🪑","Sitting Catch",1,"2","120s","3+",
    ["Sit on the floor or a chair.","Short throws only.","Catch with both hands."],
    "15 clean catches wins.",
    "No standing jumps.",
    "Perfect for small spaces."),
  m(26,"Indoor Compact","🚪","Doorway Distance",1,"2","90s","4+",
    ["Stand 1 meter apart.","Throw softly.","No stepping forward."],
    "12 clean catches wins.",
    "Keep balls away from lamps.",
    "Safe indoor rule."),
  m(27,"Indoor Compact","🤫","Signal Catch",1,"2-3","120s","4+",
    ["Use a simple hand signal before each throw.","Throw only after the signal.","Catcher signals back before returning."],
    "Complete 10 clean signal catches.",
    "Signals should be easy.",
    "Keep throws low."),
  m(28,"Indoor Compact","🧱","Floor Bounce Solo",1,"1","120s","6+",
    ["Stand 1 meter from a floor mark.","Toss softly so the ball bounces back.","Catch the bounce and repeat."],
    "10 clean bounce catches.",
    "Use soft tosses only.",
    "Clear space before you start."),
  m(29,"Indoor Compact","🧊","No-Run Rule",1,"2","120s","3+",
    ["Both players keep feet planted.","Soft toss only.","Catch and return."],
    "20 clean catches wins.",
    "If it gets wild, slow down.",
    "Safe default mode."),
  m(30,"Indoor Compact","🎨","Color Call Catch",2,"2","90s","5+",
    ["Place a sticker on left and right sides of the paddle.","Caller says Left or Right before the throw.","Catcher aims for that sticker."],
    "Score 8 correct color hits.",
    "Use soft tosses only.",
    "Switch caller every 5 throws."),
];

const BADGES = [
  { id:"first", icon:"⭐", name:"First Steps", req:"Complete 1 mission",
    check: (done)=>done.size>=1 },
  { id:"speedy", icon:"⚡", name:"Speed Demon", req:"Complete all Reflex Rush",
    check: (done)=>missions.filter(x=>x.pack==="Reflex Rush" && done.has(x.id)).length>=6 },
  { id:"sharp", icon:"🎯", name:"Aim Star", req:"Complete all Aim Master",
    check: (done)=>missions.filter(x=>x.pack==="Aim Master" && done.has(x.id)).length>=6 },
  { id:"zen", icon:"🧘", name:"Calm Hero", req:"Complete all Focus Control",
    check: (done)=>missions.filter(x=>x.pack==="Focus Control" && done.has(x.id)).length>=6 },
  { id:"team", icon:"👥", name:"Team Player", req:"Complete all Team Duo",
    check: (done)=>missions.filter(x=>x.pack==="Team Duo" && done.has(x.id)).length>=6 },
  { id:"indoor", icon:"🏠", name:"Indoor Hero", req:"Complete all Indoor Compact",
    check: (done)=>missions.filter(x=>x.pack==="Indoor Compact" && done.has(x.id)).length>=6 },
  { id:"champ", icon:"🏆", name:"Champion", req:"Complete all 30 missions",
    check: (done)=>done.size>=30 },
];
