// Data: missions, badges, packs helpers
const PACKS = [
  { key:"all", name:"All Packs" },
  { key:"Reflex Rush", name:"Reflex Rush" },
  { key:"Aim Master", name:"Aim Master" },
  { key:"Focus Control", name:"Focus Control" },
  { key:"Team Duo", name:"Team Duo" },
  { key:"Indoor Compact", name:"Indoor Compact" },
];

function m(id, pack, icon, title, difficulty, players, time, age, steps, win, safety, tip){
  return { id, pack, icon, title, difficulty, players, time, age, steps, win, safety, tip };
}

// 30 missions (5 packs × 6)
const missions = [
  // Reflex Rush (6)
  m(1,"Reflex Rush","⚡","Flash Catch",1,"2","45s","3+",
    ["Stand about 2 big steps apart (≈2 m).","Throw gently and quickly.","Count your clean catches!"],
    "Catch as many times as you can in 45 seconds!",
    "Keep throws below face level.",
    "Go slower for younger kids."),
  m(2,"Reflex Rush","🟢","Go / Stop Catch",1,"2-3","60s","4+",
    ["Throw only when someone says “GO”.","Freeze when someone says “STOP”.","Continue until timer ends."],
    "No drops during STOP = bonus point.",
    "Freeze means no throwing.",
    "Great for attention + control."),
  m(3,"Reflex Rush","👏","Clap-Then-Catch",2,"2","60s","6+",
    ["Throw gently.","Catcher claps once, then catches.","Switch roles after 10 throws."],
    "10 clean catches each wins.",
    "If it feels hard, remove the clap.",
    "Start with slow throws."),
  m(4,"Reflex Rush","🔁","Switch Hands",2,"2","90s","6+",
    ["Catch with right hand.","Next catch with left hand.","Alternate every throw."],
    "First to 12 clean catches wins.",
    "Keep distance steady.",
    "Builds both-hand coordination."),
  m(5,"Reflex Rush","🧊","Freeze & Catch",1,"2","60s","4+",
    ["After each catch, freeze 2 seconds.","Then throw back softly.","Repeat."],
    "No moving during freeze = win.",
    "No running.",
    "Simple indoor/outdoor game."),
  m(6,"Reflex Rush","🔊","Echo Count",1,"2","60s","3+",
    ["Throw and say the number aloud.","Catcher repeats the number.","Then throws back."],
    "Reach 15 without mistakes.",
    "Stay calm if mistakes happen.",
    "Adds memory + focus."),

  // Aim Master (6)
  m(7,"Aim Master","🎯","Center Hit",1,"2","90s","3+",
    ["Aim for the middle of the paddle.","Soft arc throws.","Switch after 10 throws."],
    "Most center hits wins.",
    "No hard throws.",
    "Start closer for younger kids."),
  m(8,"Aim Master","🟧","Landing Zone",1,"1-2","90s","4+",
    ["Imagine a circle in front of you.","Throw so the ball lands in it.","Catch after the bounce (optional)."],
    "5 clean landings wins.",
    "Bounce is optional.",
    "Great in a hallway/yard."),
  m(9,"Aim Master","📏","Distance Ladder",2,"2","120s","5+",
    ["Start 1 meter apart.","After 3 clean catches, step back 1 step.","Keep going."],
    "Farthest distance wins.",
    "Stop if throws get wild.",
    "Smooth, gentle arcs only."),
  m(10,"Aim Master","🧠","Two-Step Throw",2,"2","90s","6+",
    ["Take one step forward.","Throw softly.","Step back and repeat."],
    "10 clean throws wins.",
    "Keep below face level.",
    "Adds body control."),
  m(11,"Aim Master","🪙","Slow Arc",1,"2","90s","3+",
    ["Throw high and slow.","Catcher waits calmly.","Catch with both hands if needed."],
    "10 slow catches wins.",
    "No rushing.",
    "Perfect for younger kids."),
  m(12,"Aim Master","📍","Corner Aim",2,"2","120s","6+",
    ["Pick a ‘corner’ area of the paddle.","Aim there every throw.","Switch corners after 5."],
    "Most correct-corner hits wins.",
    "Keep throws gentle.",
    "Hard mode for older kids."),

  // Focus Control (6)
  m(13,"Focus Control","🧘","Quiet Round",1,"2","120s","4+",
    ["No talking challenge.","Slow throws only.","Count with fingers silently."],
    "12 clean catches without talking.",
    "Stop if someone needs a break.",
    "Great for calm focus."),
  m(14,"Focus Control","🐢","Slow Motion",1,"2","120s","3+",
    ["Move slowly like a turtle.","Throw slowly.","Catch slowly."],
    "No drops in 2 minutes.",
    "No sudden runs.",
    "Fun + safe indoors."),
  m(15,"Focus Control","👀","Eyes on Ball",1,"2","90s","3+",
    ["Catcher says “I SEE IT”.","Throw gently.","Catcher catches and repeats."],
    "Reach 15 clean catches.",
    "Keep distance stable.",
    "Builds tracking skill."),
  m(16,"Focus Control","🫁","Breathe Catch",2,"2","120s","6+",
    ["Breathe in while waiting.","Breathe out while catching.","Then throw back."],
    "10 calm catches in a row.",
    "If dizzy, stop.",
    "Adds calm control."),
  m(17,"Focus Control","🪞","Mirror Moves",2,"2","120s","6+",
    ["One player does a small pose.","Other copies it.","Then throw and catch."],
    "Copy + catch 8 times wins.",
    "Keep poses simple.",
    "Funny + focused."),
  m(18,"Focus Control","🔟","Count to Ten",1,"2","90s","3+",
    ["Count every clean catch.","If you drop, restart.","Try again."],
    "Reach 10 clean catches.",
    "No stress, just retry.",
    "Classic confidence builder."),

  // Team Duo (6)
  m(19,"Team Duo","👨‍👩‍👧‍👦","Circle Pass",2,"3-6","180s","4+",
    ["Make a small circle.","Pass to anyone (not same person twice).","Keep it gentle."],
    "Complete 2 full minutes with no drops.",
    "Keep space between kids.",
    "Perfect party mode."),
  m(20,"Team Duo","🏁","Relay Pass",2,"4+","180s","5+",
    ["Make two lines (two teams).","Pass down the line.","Last player goes to front."],
    "First team to 20 passes wins.",
    "No running if indoors.",
    "Keep throws low."),
  m(21,"Team Duo","🧑‍✈️","Captain Calls",2,"3+","150s","6+",
    ["One captain chooses the next target.","Captain says a name.","Throw to that person."],
    "No wrong throws in 2 minutes.",
    "Captain must be kind.",
    "Great listening practice."),
  m(22,"Team Duo","🛡️","Team Save",2,"3-5","180s","6+",
    ["If a ball drops, another player ‘saves’ it.","Resume immediately.","Keep count."],
    "10 saves total wins.",
    "No diving on hard floors.",
    "Use soft balls only."),
  m(23,"Team Duo","🔄","Partner Swap",2,"4+","180s","6+",
    ["Play 6 catches with a partner.","Then swap partners.","Repeat."],
    "Most clean swaps wins.",
    "Swap calmly, no pushing.",
    "Keeps everyone included."),
  m(24,"Team Duo","🏆","2v2 Mini Match",3,"4","240s","7+",
    ["Two teams of two.","Each team tries 10 clean catches.","Miss = restart that team’s count."],
    "First team to 10 wins.",
    "Stop if too competitive.",
    "Keep it friendly."),

  // Indoor Compact (6)
  m(25,"Indoor Compact","🪑","Sitting Catch",1,"2","120s","3+",
    ["Sit on the floor or a chair.","Short throws only.","Catch with both hands."],
    "15 clean catches wins.",
    "No standing jumps.",
    "Perfect for small spaces."),
  m(26,"Indoor Compact","🚪","Doorway Distance",1,"2","90s","4+",
    ["Stand 1 meter apart.","Throw softly.","No stepping forward."],
    "12 clean catches wins.",
    "Keep balls away from lamps.",
    "Safe indoor rule."),
  m(27,"Indoor Compact","🤫","Silent Catch",1,"2-3","120s","4+",
    ["No talking challenge.","Soft throws only.","Count with fingers."],
    "No drops for 2 minutes.",
    "Take breaks if needed.",
    "Calm + fun."),
  m(28,"Indoor Compact","🧱","Wall Assist (Solo)",2,"1","120s","6+",
    ["Stand 1 meter from a wall.","Throw gently to wall.","Catch the return."],
    "10 clean wall catches.",
    "Use a soft throw only.",
    "Adult checks surroundings."),
  m(29,"Indoor Compact","🧊","No-Run Rule",1,"2","120s","3+",
    ["Both players keep feet planted.","Soft toss only.","Catch and return."],
    "20 clean catches wins.",
    "If it gets wild, slow down.",
    "Safe default mode."),
  m(30,"Indoor Compact","🎯","Tiny Target",2,"2","120s","6+",
    ["Aim for the center.","Short throws.","Switch after 10."],
    "Most center hits wins.",
    "No hard throws indoors.",
    "Great skill drill."),
];

const BADGES = [
  { id:"first", icon:"⭐", name:"First Steps", req:"Complete 1 mission",
    check: (done)=>done.size>=1 },
  { id:"speedy", icon:"⚡", name:"Speed Demon", req:"Complete all Reflex Rush",
    check: (done)=>missions.filter(x=>x.pack==="Reflex Rush" && done.has(x.id)).length>=6 },
  { id:"sharp", icon:"🎯", name:"Aim Star", req:"Complete all Aim Master",
    check: (done)=>missions.filter(x=>x.pack==="Aim Master" && done.has(x.id)).length>=6 },
  { id:"zen", icon:"🧘", name:"Calm Hero", req:"Complete all Focus Control",
    check: (done)=>missions.filter(x=>x.pack==="Focus Control" && done.has(x.id)).length>=6 },
  { id:"team", icon:"👥", name:"Team Player", req:"Complete all Team Duo",
    check: (done)=>missions.filter(x=>x.pack==="Team Duo" && done.has(x.id)).length>=6 },
  { id:"indoor", icon:"🏠", name:"Indoor Hero", req:"Complete all Indoor Compact",
    check: (done)=>missions.filter(x=>x.pack==="Indoor Compact" && done.has(x.id)).length>=6 },
  { id:"champ", icon:"🏆", name:"Champion", req:"Complete all 30 missions",
    check: (done)=>done.size>=30 },
];

