import {playerContext} from '../components/player-context.js';
import {historySummary} from '../repository/history-summary.js';
import {equipmentText} from '../catalog.js';
import {el,heading} from '../components/dom.js';import {button} from '../components/button.js';
// Transient catalogue controls only: no player identity, telemetry or persistence.
const filters=new Map();
const packs=[{ids:[7,8,9,10,11,12],tr:'Hedefe doğru',en:'Bullseye!'}, {ids:[13,14,15,16,17,18],tr:'Odaklan ve oyna',en:'Zen Mode'}, {ids:[19,20,21,22,23,24],tr:'Takım oyunu',en:'Team Up'}, {ids:[25,26,27,28,29,30],tr:'Dar alanda oyun',en:'Indoor Fun'}, {ids:[31,32,33,34,35,36],tr:'Açık hava',en:'Outdoor'}, {ids:[1,2,3,4,5,6],tr:'Hızlı eller',en:'Lightning Hands'}];
export function supportsPlayers(value,count){const digits=String(value).match(/\d+/g)?.map(Number)||[];return !count|| (String(value).includes('+')?count>=digits[0]:digits.length>1?count>=digits[0]&&count<=digits[1]:count===digits[0]);}
export default function view({ui,state,send,cp,presentation,assetManifest,personal,catalog={missions:[]}}){
 const tr=state.locale==='tr',s=el('section');s.dataset.view='discovery';s.classList.add('customer-layout');
 const header=el('header',undefined,'customer-header'),logo=el('img');logo.src=new URL('../../assets/mission-illustrations/m25/jumvi-logo.webp',import.meta.url);logo.alt='JUMVI';logo.width=80;logo.height=80;logo.className='brand';header.append(logo,el('span',tr?'OYNA · HAREKET ET':'PLAY · MOVE','customer-eyebrow'));s.append(header);
 s.append(button(ui.back,()=>send('BACK'),{kind:'link'}),heading(ui.titles.discovery),el('p',tr?'Birlikte oynayacağınız görevi seç.':'Pick a game to play together.'));
 const selected=catalog.missions.find(m=>m.id===state.mission.id),featuredPath=presentation?.missions?.[selected?.id]?.hero?.images?.[0];
 if(selected&&featuredPath){const card=el('article',undefined,'featured-mission'),copy=el('div',undefined,'featured-copy');copy.append(el('p',tr?'OYUNA DEVAM':'KEEP PLAYING','customer-eyebrow'),el('h2',selected.titles[state.locale]),el('p',equipmentText(selected,state.locale)),button(tr?'Bu görevle oyna':'Play this mission',()=>send('SELECT_MISSION',{missionId:selected.id}),{kind:'primary'}));const image=el('img');image.src=new URL('../../'+featuredPath,import.meta.url);image.alt='';const metadata=assetManifest?.assets.find(x=>x.path===featuredPath);if(metadata){image.width=metadata.width;image.height=metadata.height;}card.append(copy,image);s.append(card);}
 s.append(playerContext({state,personal,send,ui,catalog},{progress:true}));
 const actor=personal?.snapshot?.players.find(p=>p.id===personal.actorId),completed=actor?historySummary(personal.snapshot.records,actor.id,catalog.missions.map(m=>m.id)).byMission:new Map();
 const current=filters.get(state.locale)||{players:0,remaining:false},form=el('div',undefined,'mission-filters');
 const playerLabel=el('label',tr?'Kaç oyuncu var?':'How many players?'),players=el('select');players.id='mission-player-filter';playerLabel.htmlFor=players.id;
 for(const n of [0,2,3,4]){const option=el('option',n?`${n} ${tr?'oyuncu':'players'}`:tr?'Tüm oyuncu sayıları':'Any player count');option.value=String(n);players.append(option);}players.value=String(current.players);
 const count=el('p',undefined,'muted');count.setAttribute('role','status');count.setAttribute('aria-live','polite');
 const groups=packs.map(pack=>{const section=el('section',undefined,'mission-group'),title=el('h2',tr?pack.tr:pack.en),groupCount=el('p',undefined,'muted group-count'),list=el('ul',undefined,'mission-list');section.append(title,groupCount,list);return {pack,section,list,groupCount};}),rows=[];
 const shortcuts=el('nav',undefined,'pack-shortcuts');shortcuts.setAttribute('aria-label',tr?'Görev grupları':'Mission groups');for(const g of groups){const h=g.section.querySelector('h2');h.tabIndex=-1;g.shortcut=button(tr?g.pack.tr:g.pack.en,()=>{h.focus({preventScroll:true});h.scrollIntoView({block:'start'});},{kind:'link'});shortcuts.append(g.shortcut);}
 const remainingLabel=el('label',undefined,'remaining-filter'),remaining=el('input');remaining.type='checkbox';remaining.checked=!!actor&&!!current.remaining;remaining.disabled=!actor;remainingLabel.hidden=!actor;remainingLabel.append(remaining,el('span',tr?'Henüz tamamlanmayanlar':'Not completed yet'));
 const filterHint=el('p',actor?(tr?'Bu cihazda seçili oyuncuya kaydedilen bildirimlere göre.':'Based on reports saved for the selected player on this device.'):(tr?'Tamamlananları oyuncu geçmişine göre ayırabilirsin. Oyuncusuz oynamaya devam edebilirsin.':'Completed missions are shown for an optional local player. You can keep playing as a guest.'),'muted');
 filterHint.hidden=!actor;
 for(const m of catalog.missions){const li=el('li');const path=presentation?.missions?.[m.id]?.hero?.images?.[0];if(path){const image=el('img');image.src=new URL('../../'+path,import.meta.url);image.alt='';image.loading='lazy';const metadata=assetManifest?.assets.find(x=>x.path===path);if(metadata){image.width=metadata.width;image.height=metadata.height;}image.className='mission-thumbnail';li.append(image);}const body=el('div',undefined,'mission-card-body');body.append(el('h3',m.titles[state.locale]));if(completed.has(m.id)){const badge=el('p',tr?'✓ Tamamlandı':'✓ Completed','mission-completed');badge.setAttribute('aria-label',tr?`${actor.nickname||actor.label}: tamamlandı olarak kaydedildi`:`${actor.nickname||actor.label}: saved as completed`);body.append(badge);}body.append(el('p',equipmentText(m,state.locale)),button(completed.has(m.id)?tr?'Tekrar oyna':'Play again':tr?'Görevi aç':'Open mission',()=>send('SELECT_MISSION',{missionId:m.id})));li.append(body);li.querySelector('button').setAttribute('aria-label',`${tr?'Görevi aç':'Open mission'}: ${m.titles[state.locale]}`);li.dataset.missionId=m.id;const group=groups.find(g=>g.pack.ids.includes(Number(m.id.slice(1))));group.list.append(li);rows.push({li,m,group});}
 const update=()=>{const n=Number(players.value);let found=0;for(const {li,m} of rows){li.hidden=!(supportsPlayers(m.players,n))||(remaining.checked&&completed.has(m.id));if(!li.hidden)found++;}filters.set(state.locale,{players:n,remaining:remaining.checked});for(const g of groups){const shown=rows.filter(r=>r.group===g&&!r.li.hidden).length;g.section.hidden=shown===0;g.shortcut.hidden=shown===0;const done=g.pack.ids.filter(n=>completed.has('m'+String(n).padStart(2,'0'))).length;g.groupCount.textContent=actor?(tr?`${done}/6 tamamlandı · ${shown} görev gösteriliyor`:`${done}/6 completed · ${shown} missions shown`):(tr?`${shown} görev`:`${shown} missions`);}count.textContent=found?tr?`${found} görev gösteriliyor`:`${found} missions shown`:remaining.checked?(tr?'Bu filtrelerde tamamlanmamış görev kalmadı.':'No unfinished missions match these filters.'):(tr?'Bu oyuncu sayısı için görev bulunamadı.':'No missions for this player count.');};
 players.addEventListener('change',update);remaining.addEventListener('change',update);
 form.append(playerLabel,players,remainingLabel,filterHint,button(tr?'Filtreleri temizle':'Clear filters',()=>{players.value='0';remaining.checked=false;update();players.focus();},{kind:'link'}));s.append(form,count,shortcuts,...groups.map(g=>g.section),button(ui.back,()=>send('BACK'),{kind:'link'}));update();return s;
}
