import v0 from './entry.js';
import v1 from './discovery.js';
import v2 from './help.js';
import v3 from './active.js';
import v4 from './interrupted.js';
import v5 from './stopped.js';
import v6 from './report.js';
import v7 from './attribution.js';
import v8 from './record-result.js';
import v9 from './guest.js';
import v10 from './group.js';
import v11 from './availability.js';
import v12 from './recovery.js';
import v13 from './adult.js';
import v14 from './management.js';
import v15 from './returning.js';
import v16 from './new-player.js';
export const views={'entry':v0,'discovery':v1,'help':v2,'active':v3,'interrupted':v4,'stopped':v5,'report':v6,'attribution':v7,'record-result':v8,'guest':v9,'group':v10,'availability':v11,'recovery':v12,'adult':v13,'management':v14,'returning':v15,'new-player':v16};
