import test from 'node:test';import assert from 'node:assert/strict';import {AudioController} from '../../src/client/media/audio-controller.js';import {readResume,writeResume} from '../../src/client/resume.js';import {initialState,transition} from '../../src/client/state/app.js';
const mission={id:'m25',mechanicsVersion:'fixture-v1',ready:true},init=()=>initialState({documentId:'test',mission}),act=(s,type,d={})=>transition(s,{type,...d,documentId:s.documentId,revision:s.revision});
function storage(){let v=null;return {getItem(){return v;},setItem(k,value){v=value;},removeItem(){v=null;}};}
function deferredMedia(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {paused:false,ended:false,play:()=>promise,pause(){this.paused=true;},resolve,reject};}
test('resume stores only a minimal round summary; never report, target or identity',()=>{const st=storage();let s=act(init(),'START',{id:'one'});s=act(act(s,'STOP'),'REPORT',{id:'r',value:'complete'});assert(writeResume(st,s));assert.deepEqual(Object.keys(JSON.parse(st.getItem())).sort(),['id','mechanicsVersion','missionId','schema','state']);const r=readResume(st,mission);assert.equal(r.round.id,'one');assert.equal(r.round.state,'stopped');assert.equal(r.round.report,undefined);});
test('active summary restores to interruption; mismatched version, corrupt or denied storage never resumes',()=>{const st=storage();writeResume(st,act(init(),'START',{id:'one'}));assert.equal(readResume(st,mission).round.state,'interrupted');assert.equal(readResume(st,{...mission,mechanicsVersion:'other'}).kind,'unknown');st.setItem('', '{broken');assert.equal(readResume(st,mission).kind,'unknown');assert.equal(readResume(null,mission).kind,'unknown');assert.equal(writeResume(null,init()),false);});
test('report selection from entry creates no round; correction has same identity and new revision',()=>{let s=act(init(),'REPORT_OPEN');assert.equal(s.round,null);s=act(s,'REPORT',{id:'one',value:'complete'});s=act(s,'EDIT_REPORT');s=act(s,'REPORT',{id:'two',value:'early'});assert.equal(s.report.id,'one');assert.equal(s.report.value,'early');assert.equal(s.report.revision,2);assert.equal(s.round,null);});
test('missing critical asset permits recovery context but prevents start/resume',()=>{const s={...init(),mission:{...mission,ready:false}};const restored=act(s,'RESTORE',{round:{id:'one',missionId:'m25',mechanicsVersion:'fixture-v1',state:'interrupted'}});assert.equal(restored.screen,'interrupted');assert.equal(act(restored,'RESUME'),restored);assert.equal(act(restored,'REPLAY',{id:'new'}),restored);});
test('audio is default off, absent/unapproved narration never falls back or plays',async()=>{let creations=0;const a=new AudioController({createMedia(){creations++;}});assert.equal(a.preference,false);await a.toggle(null,'ctx');assert.equal(a.playback,'unavailable');assert.equal(a.preference,false);assert.equal(creations,0);await a.replay({url:'fake',context:'ctx'},'ctx');assert.equal(creations,0);});
test('pending toggle mute, stop, navigation and hidden all pause late audio',async()=>{for(const mode of ['mute','stop','navigation','hidden']){const m=deferredMedia(),a=new AudioController({createMedia:()=>m});const request=a.toggle({url:'fixture',context:'ctx'},'ctx');assert.equal(a.playback,'pending');if(mode==='mute')await a.toggle(null,'ctx');else a.cancel();m.resolve();assert.equal(await request,false);assert(m.paused);assert.equal(a.preference,false);assert.equal(a.playback,'idle');}});
test('old play resolution cannot interrupt or enable a newer request',async()=>{const old=deferredMedia(),fresh=deferredMedia(),q=[old,fresh],a=new AudioController({createMedia:()=>q.shift()});const first=a.request({url:'one',context:'a'},'a');const second=a.request({url:'two',context:'b'},'b');fresh.resolve();assert(await second);old.resolve();assert.equal(await first,false);assert(old.paused);assert(!fresh.paused);assert.equal(a.playback,'playing');a.cancel();assert(fresh.paused);});
test('natural end retains preference, navigation never auto plays; rejected request returns off',async()=>{const m=deferredMedia(),a=new AudioController({createMedia:()=>m});const p=a.request({url:'fixture',context:'c'},'c');m.resolve();await p;m.onended();assert.equal(a.playback,'ended');assert(a.preference);a.cancel();assert(a.preference);assert.equal(a.playback,'idle');const bad=deferredMedia(),b=new AudioController({createMedia:()=>bad});const r=b.request({url:'fixture',context:'c'},'c');bad.reject(Error('NotAllowed'));assert.equal(await r,false);assert.equal(b.playback,'unavailable');assert.equal(b.preference,false);});
