/* Immutable release manifest is embedded by the build. No forced activation or client takeover. */
const MANIFEST=__MANIFEST__;
const RELEASE=MANIFEST.release,PREFIX='jumvi-lock09-',SHELL=PREFIX+RELEASE+'-shell',CONTENT=PREFIX+RELEASE+'-content';
const known=new Map(MANIFEST.files.map(f=>[f.path,f]));
const shellKey=p=>['/','/index.html'].includes(p)?'/index.html':['/tr','/tr/','/tr/index.html'].includes(p)?'/tr/index.html':p;
function allowed(request){const u=new URL(request.url);return request.method==='GET'&&u.origin===self.location.origin&&!u.search&&!request.headers.has('Authorization')&&known.has(shellKey(u.pathname));}
const hex=buf=>[...new Uint8Array(buf)].map(n=>n.toString(16).padStart(2,'0')).join('');
async function valid(response,entry){if(response.status!==200||response.type==='opaque'||response.redirected||/private/i.test(response.headers.get('cache-control')||'')||/cookie|authorization/i.test(response.headers.get('vary')||''))return false;const mime=response.headers.get('content-type')||'';if(!mime.toLowerCase().startsWith(entry.mime))return false;const bytes=await response.clone().arrayBuffer();return bytes.byteLength===entry.bytes&&hex(await crypto.subtle.digest('SHA-256',bytes))===entry.sha256;}
const cacheName=path=>path.endsWith('.html')||path.includes('/client/')?SHELL:CONTENT;
async function obtain(path){const key=shellKey(path),entry=known.get(key);if(!entry)throw Error('Not public');const cache=await caches.open(cacheName(key)),hit=await cache.match(key);if(hit&&await valid(hit,entry))return hit;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(new Request(key,{credentials:'omit',cache:'no-store',signal:controller.signal}));if(!await valid(r,entry))throw Error('Release mismatch');await cache.put(key,r.clone());return r;}finally{clearTimeout(timer);}}
self.addEventListener('install',event=>event.waitUntil((async()=>{try{for(const path of MANIFEST.precache)await obtain(path);}catch(e){await caches.delete(SHELL);await caches.delete(CONTENT);throw e;}})()));
// Retain previous release and unrelated/legacy caches. No cache deletion at activation.
self.addEventListener('activate',()=>{});
self.addEventListener('message',event=>{if(event.data?.type!=='CACHE_MISSION'||event.data.release!==RELEASE)return;const ids=MANIFEST.missions[event.data.id];if(!ids)return;event.waitUntil((async()=>{try{for(const p of ids)await obtain(p);event.ports[0]?.postMessage({release:RELEASE,id:event.data.id,ready:true});}catch{event.ports[0]?.postMessage({release:RELEASE,id:event.data.id,ready:false});}})());});
self.addEventListener('fetch',event=>{const req=event.request;if(!allowed(req))return;const url=new URL(req.url),key=shellKey(url.pathname),entry=known.get(key);
 if(key.endsWith('.html')){event.respondWith((async()=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(new Request(req,{cache:'no-store',signal:controller.signal}));if(r.ok){if(await valid(r,entry))await (await caches.open(SHELL)).put(key,r.clone());return r;}}catch{}finally{clearTimeout(timer);}const hit=await (await caches.open(SHELL)).match(key);if(hit&&await valid(hit,entry)){const headers=new Headers(hit.headers);for(const key of ['content-length','transfer-encoding','connection','keep-alive'])headers.delete(key);return new Response(await hit.arrayBuffer(),{status:hit.status,statusText:hit.statusText,headers});}return new Response('Offline content unavailable',{status:503,headers:{'Content-Type':'text/plain','Cache-Control':'no-store'}});})());}
 else event.respondWith(obtain(key).catch(()=>new Response('This release asset is unavailable',{status:503,headers:{'Content-Type':'text/plain','Cache-Control':'no-store'}})));
});
