#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# CORE_ASSETS staleness guard  (run before every deploy)
#
# WHY THIS EXISTS
# The service worker serves precached CORE_ASSETS cache-first and only ever
# refetches them when CACHE_NAME changes. Those paths are intentionally
# UNVERSIONED (no ?v=) so the precache can match them literally — which means a
# changed file at the same path is invisible to a returning visitor until
# CACHE_NAME is bumped. _headers fixed the HTTP layer; this is the layer below
# it. Coach Leo's model shipped stale for exactly this class of reason.
#
# WHAT IT DOES
# Hashes every file listed in service-worker.js CORE_ASSETS and compares against
# tools/core-assets.lock. If any hash changed while CACHE_NAME stayed the same,
# it FAILS and tells you to bump CACHE_NAME.
#
#   ./tools/check-core-assets.sh           # verify (exit 1 on drift)
#   ./tools/check-core-assets.sh --update  # after bumping CACHE_NAME, re-lock
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail
cd "$(dirname "$0")/.."

SW="service-worker.js"
LOCK="tools/core-assets.lock"
MODE="${1:-verify}"

CACHE_NAME=$(grep -oE 'CACHE_NAME *= *"[^"]+"' "$SW" | head -1 | sed 's/.*"\(.*\)"/\1/')
if [ -z "$CACHE_NAME" ]; then echo "FAIL: could not read CACHE_NAME from $SW"; exit 1; fi

# Pull the quoted paths out of the CORE_ASSETS array (ignore comment lines).
ASSETS=$(awk '/const CORE_ASSETS *= *\[/,/\]/' "$SW" \
  | grep -v '^\s*//' \
  | grep -oE '"/[^"]*"' | tr -d '"')

tmp=$(mktemp)
{
  echo "# GENERATED by tools/check-core-assets.sh — do not hand-edit."
  echo "# Bump CACHE_NAME in service-worker.js, then re-run with --update."
  echo "CACHE_NAME=$CACHE_NAME"
} >> "$tmp"

missing=0
while IFS= read -r a; do
  [ -z "$a" ] && continue
  f=".${a}"                      # "/app.js" -> "./app.js"
  if [ "$a" = "/" ]; then f="./index.html"; fi

  # /tr/index.html has no file on disk on purpose: the Worker builds it from
  # the English shell plus the locale layer, and creating a real tr/index.html
  # would make Cloudflare serve that file directly and bypass the Worker
  # entirely. Hash its actual inputs instead, so a change to any of them still
  # trips the "bump CACHE_NAME" rule the same way a real file would.
  if [ "$a" = "/tr/index.html" ]; then
    for dep in ./index.html ./tr/i18n.js ./src/worker.js; do
      if [ ! -f "$dep" ]; then echo "MISSING: $dep (input to $a)"; missing=1; fi
    done
    [ "$missing" -ne 0 ] && continue
    h=$(cat ./index.html ./tr/i18n.js ./src/worker.js | shasum -a 256 | cut -d' ' -f1)
    echo "$h  $a" >> "$tmp"
    continue
  fi

  if [ ! -f "$f" ]; then echo "MISSING: $a (listed in CORE_ASSETS, not on disk)"; missing=1; continue; fi
  h=$(shasum -a 256 "$f" | cut -d' ' -f1)
  echo "$h  $a" >> "$tmp"
done <<< "$ASSETS"

if [ "$missing" -ne 0 ]; then rm -f "$tmp"; echo "FAIL: CORE_ASSETS references files that do not exist."; exit 1; fi

if [ "$MODE" = "--update" ]; then
  mv "$tmp" "$LOCK"
  echo "Locked $(grep -c '^[0-9a-f]' "$LOCK") assets against CACHE_NAME=$CACHE_NAME"
  exit 0
fi

if [ ! -f "$LOCK" ]; then rm -f "$tmp"; echo "FAIL: $LOCK missing. Run: ./tools/check-core-assets.sh --update"; exit 1; fi

OLD_CACHE=$(grep '^CACHE_NAME=' "$LOCK" | cut -d= -f2-)
if diff -q <(grep -v '^#' "$tmp") <(grep -v '^#' "$LOCK") >/dev/null 2>&1; then
  rm -f "$tmp"; echo "OK: CORE_ASSETS unchanged (CACHE_NAME=$CACHE_NAME)"; exit 0
fi

# Something differs. If CACHE_NAME also changed, that's a correct bump.
if [ "$CACHE_NAME" != "$OLD_CACHE" ]; then
  rm -f "$tmp"
  echo "OK: assets changed AND CACHE_NAME bumped ($OLD_CACHE -> $CACHE_NAME)."
  echo "    Re-lock with: ./tools/check-core-assets.sh --update"
  exit 0
fi

echo "FAIL: precached asset(s) changed but CACHE_NAME is still '$CACHE_NAME'."
echo "      Returning visitors would keep the OLD file forever (SW serves"
echo "      precache cache-first and only refetches when CACHE_NAME changes)."
echo
echo "Changed:"
diff <(grep -v '^#' "$LOCK") <(grep -v '^#' "$tmp") | grep '^[<>]' | sed 's/^/  /'
echo
echo "Fix: bump CACHE_NAME in service-worker.js, then ./tools/check-core-assets.sh --update"
rm -f "$tmp"
exit 1
