import json
from pathlib import Path
p=Path('content/customer-presentation-v1.json');data=json.loads(p.read_text())
# Customer-facing wording only. Canonical source records, counts and role order stay unchanged.
copy={
1:(["Stand 2 big kid steps apart.","Toss quickly, but keep each toss gentle.","Catch on the blue side. Take the ball off with your free hand, then toss it back."],"How many catches can you make in 45 seconds? Try to beat your own best.","Keep tosses below chin level. Never aim at anyone’s face."),
2:(["Choose a person to call Green or Red. With 3 players, the third person can call. With 2 players, take turns calling.","Green means toss and catch. Red means freeze: no tossing or moving.","A person makes the calls. The phone does not call colors, run a timer, or make automatic sounds."],"Play for 60 seconds without tossing on Red.","When you hear Red, stop and stay still."),
3:(["Keep the paddle strapped to one hand while your partner makes a gentle toss.","Use your free hand to lightly tap your own paddle once.","Catch the ball on the blue side. Switch roles after every 10 throws."],"Make 10 clean tap-and-catches each.","Tap gently with your free hand. Keep your paddle strapped on; it has no handle."),
4:(["Catch the ball on the blue side with the hand wearing the paddle.","Use your free hand to take the ball off.","Pass the ball to the hand that is still wearing the paddle.","Carefully slide that hand out of the strap.","Put the paddle on your other hand and secure the strap.","The hand holding the ball is now free. Use it to make a gentle toss.","Make your next catch with the other paddle hand. Repeat this whole hand switch after every clean catch."],"Be the first to make 12 catches, switching paddle hands after each one.","Take your time switching hands. Never toss the paddle between hands or change hands with the ball still stuck to it. There is no handle."),
5:(["Catch the ball on the blue side, then freeze for 2 seconds.","Keep your paddle, body, and feet still, like a statue.","After the freeze, take the ball off with your free hand and toss it back."],"Make 10 catches, with a full freeze after each one.","Stay completely still during each 2-second freeze."),
6:(["Toss the ball and call out the number.","The catcher repeats the number, takes the ball off, and tosses it back.","If the ball drops, start counting again from 1."],"Count out loud together and reach 15 catches in a row.","A missed catch is okay. Take a breath and start again."),
7:(["Stand 5 big steps apart.","Make gentle rainbow-shaped tosses toward your partner’s paddle, never their head.","Flat tosses do not count. After 5 clean rainbow tosses, step back."],"Complete 3 distance levels, with 5 rainbow tosses at each level.","Use a gentle arc, not a hard throw. Let the ball come down naturally."),
8:(["Toss the ball gently in a high arc.","The catcher holds the paddle flat and still, with the blue side facing up.","Let the ball land and stick on the blue side. Do not swing at it."],"Make 8 clean landings on the paddle.","Let the ball stick. Do not swat or hit it."),
9:(["Start 1 big step apart and make 3 clean catches.","Step back half a step, then make another 3 clean catches.","Keep going until you are 3 big steps apart."],"Reach 3 big steps apart and make 3 clean catches there.","Stop if you can no longer keep your tosses controlled."),
10:(["Start 6 big kid steps apart.","Step forward as you make a gentle toss.","After the catch, step back to your starting spot. Now it’s your partner’s turn."],"Make 10 clean step-and-toss turns each.","Keep the toss gentle. The step already adds power."),
11:(["Make a gentle, controlled high toss toward the paddle.","The catcher waits calmly for the ball to come down.","Catch it as it drops onto the blue side of the paddle."],"Make 10 patient catches from high tosses.","Take your time. Do not swing the paddle at the ball."),
12:(["Stand 6 big steps apart.","The catcher holds the paddle at chest height, with its blue side facing the ball.","Toss toward the blue paddle face, never the person’s chest. A toss that is too high or too low does not count."],"Make 10 catches in a row on the paddle at chest height.","Aim at the blue paddle face, never anyone’s body."),
13:(["Play without talking while the physical game is underway.","After each catch, show the count with your fingers. If anyone speaks, start again from 1.","You can listen to instructions before playing or when you ask for Help. Going back to the game does not start the narration."],"Make 12 catches without talking.","Take a breath before each toss."),
14:(["Make 5 very slow throws.","Then make 5 throws at a medium pace.","Repeat those two sets once more. Keep your feet in place."],"Finish all 20 throws without dropping the ball.","Keep your feet planted. Only your arms move."),
15:(["Before a catch, the catcher calls, “I see it!”","Wait until you hear the call, then toss.","Catch, say “I see it!” again, and toss the ball back."],"Make 15 catches with the “I see it!” call.","Stay the same distance apart. No surprise tosses."),
16:(["The thrower counts “1, 2, 3” out loud.","Release the ball right on “3.”","The catcher counts “1, 2, 3” before tossing it back."],"Make 10 catches with tosses timed to the count.","Count calmly and keep a steady rhythm."),
17:(["The leader shows a comfortable paddle pose: high, low, or gently tilted.","The catcher copies that pose relative to their own body.","The leader makes a gentle toss with their free hand.","The catcher holds the matching pose and catches on the blue side.","The catcher takes the ball off with their free hand and sends a normal return pass to the leader.","Keep the same leader for 5 challenge tosses, then switch roles. Return passes do not count toward those 5."],"Complete 8 mirror-and-catch rounds.","Use comfortable poses. Do not stretch too far or tilt sharply. Catch on the blue side."),
18:(["Count every clean catch out loud together.","If the ball drops, start again from 1.","No pressure. Have another go together."],"Make 10 catches without dropping the ball.","Starting over is part of the game. Keep it relaxed."),
19:(["Stand in a circle, each wearing a paddle.","Toss to anyone, but never to the same person twice in a row.","Keep every toss gentle."],"Play for 2 full minutes. Count the drops and try to beat your own record.","Leave space between players. Do not crowd together."),
20:(["Make 2 lines with 4 players. Use just 1 ball.","Catch on the blue side. Take the ball off with your free hand, then toss it to the next player.","After your catch-and-pass turn, stay standing and shuffle sideways to the back of your line."],"Make 20 passes together across both lines.","Stay on your feet and move sideways. No running or crab-walking on your hands. Never put your weight on a hand wearing a paddle."),
21:(["Play with 3 people, 3 paddles, and 1 ball. Two players face each other, with the third in the middle.","The outside players toss to each other below face level.","If the middle player catches the ball on the paddle, they walk over and trade places with the person who threw it."],"Make 6 catches in the middle. Everyone gets a turn.","Keep tosses below face level. Walk when trading places. Do not dive for the ball."),
22:(["Four players stand in a square, each wearing a paddle.","One player tosses to anyone.","After each catch, everyone steps clockwise. Then make the next toss."],"Make 20 catches, with everyone moving after each catch.","Move calmly and leave room for each other."),
23:(["Four players share 1 ball. Only one pair plays at a time.","When that pair makes 6 clean catches, give the ball to the next pair.","Play every pairing once. Four players make 6 different pairs."],"Finish all 6 pairings, with 6 clean catches per pair.","Change partners calmly. Use only 1 ball, with only 1 pair playing at a time."),
24:(["Make 2 teams of 2. Share 1 ball and take turns playing.","One team makes 5 clean catches, then passes the ball to the other team.","Add both teams’ catches to one shared total."],"Reach 40 catches together.","Only one team plays at a time. You can use 4 paddles, but never run two games at once."),
25:(["Stay seated on the floor or a chair. Make a short, gentle toss with your free hand.","Catch on the blue side. Take the ball off with your free hand, then gently toss it back."],"Make 15 clean catches while seated.","Keep tosses gentle and below face level. Stay 1–3 meters apart and play with a grown-up supervising. Move breakable things out of the way."),
26:(["Stand just 1 big step apart.","Toss gently without stepping forward.","Keep your feet in place the whole time."],"Make 12 clean catches in your small space.","Watch for lamps, shelves, and other nearby objects."),
27:(["Catch the ball on the blue side.","Take the ball off with your free hand and keep it in that hand.","Use the hand wearing the paddle to show your chosen signal to the next catcher.","Wait until they see the signal, then toss gently with your free hand. No signal means no toss."],"Make 10 catches with your secret signal.","Choose a simple paddle signal that is easy to see. You do not need finger gestures. Use only 1 ball."),
28:(["The thrower secretly chooses left, right, or center.","Wait 3 seconds without giving any hints.","Before the toss, the catcher guesses and moves the paddle into position."],"Guess correctly 8 times out of 12.","Keep tosses gentle and stay a predictable distance apart. Only the direction is a surprise."),
29:(["Both players keep their feet in place.","Make gentle tosses.","Catch and toss back without chasing the ball."],"Make 20 clean catches.","If tosses get hard to control, slow down together."),
30:(["Before each challenge toss, the caller says “Left” or “Right.”","The catcher moves the paddle to that side of their own body, with the blue side facing the ball.","The caller tosses straight and gently toward that paddle, never toward the person’s body.","The catch counts as correct only if the ball sticks to the blue side on the called side.","The catcher takes the ball off with their free hand and makes a normal return pass. Returns need no call and do not count.","The same caller makes 5 challenge tosses, then you switch roles. Do not include return passes in those 5."],"Make 8 correct catches on the called side.","Aim at the blue paddle face on the called side, never at the person. Keep tosses straight and gentle."),
31:(["Stand 6 big steps apart.","Make a controlled high toss. Never aim at anyone’s face or head.","Watch the ball come down and catch it on the blue side."],"Make 10 catches from high tosses.","The ball travels in a high arc, but the target is always the paddle."),
32:(["Each player picks a home base, such as a shadow, sidewalk square, or patch of grass.","Toss and catch from your base. Keep your feet in place.","Stepping off your base counts as a miss."],"Make 10 catches while staying on your base.","Choose safe, flat ground for each base."),
33:(["Start 6 big kid steps apart.","Make 3 clean catches, then both step back 2 big steps.","Keep going and remember your best distance."],"Try to beat your own distance record.","As you move farther apart, use controlled arcs toward the paddle. Do not throw harder at a person."),
34:(["The thrower tosses a little ahead of the catcher, not too far.","The catcher runs to meet the ball.","Catch it on the paddle before it reaches the ground."],"Make 7 running catches.","Choose a clear running area with no obstacles."),
35:(["Toss just above the catcher’s normal paddle reach, never at their head. Do not toss too high.","The catcher waits for the toss before jumping.","Jump and catch on the blue side while in the air. Switch roles every 5 throws."],"Make 8 jumping catches.","Use flat, soft ground. Grass is best. Land on both feet before taking the ball off."),
36:(["Start close together and toss back and forth.","After every 5 clean catches, both step back 1 big step.","See how far apart you can get while keeping the rally going."],"Reach 20 catches without dropping the ball.","Stop stepping back if you cannot keep the tosses controlled.")}
for i,(steps,goal,safe) in copy.items():
 m=data['missions'][f'm{i:02}'];m['customerCopy']={'en-US':{'steps':steps,'goal':goal,'safety':safe}}
# Setup contains essential canonical mechanics. Preserve it while replacing technical vocabulary.
for i in [4,17,27,30]:
 c=json.load(open(f'content/missions/m{i:02}.json'))['locale']['en-US']
 setup=c['setup'].replace('Mirror the pose relative to your own body, not an identical angle in the room.','Match the pose on your own body; you do not need the same angle in the room.').replace('Left and right are from the catcher’s own body perspective.','Left and right mean the catcher’s own left and right.')
 data['missions'][f'm{i:02}']['customerCopy']['en-US']['setup']=setup
# Entry and active pilot summaries use the same natural vocabulary; no mechanics omitted.
for m in data['missions'].values():
 def friendly(obj):
  if isinstance(obj,dict):
   for k,v in obj.items():
    if k=='en-US' and isinstance(v,str):obj[k]=v.replace('detach','take the ball off').replace('Detach','Take the ball off').replace('neutral reset pass','normal return pass').replace('sticky catch','catch with the ball sticking to the paddle').replace('blue front','blue side')
    elif k!='customerCopy':friendly(v)
  elif isinstance(obj,list):
   for v in obj:friendly(v)
 friendly(m)
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
